---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: El servicio de BlueXP backup and recovery necesita primero descubrir los datos para que pueda utilizarlo. Durante el descubrimiento, BlueXP backup and recovery analiza todos los volúmenes y archivos en los entornos de trabajo de su organización. 
---
= Limitaciones conocidas de la BlueXP backup and recovery para cargas de trabajo de Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.



== Soporte del ciclo de vida de los clones

* No se admite la clonación desde el almacenamiento de objetos.
* Las operaciones de clonación masiva no son compatibles con clones a pedido.
* No se admite la selección de grupos I.
* No se admite la selección de opciones de QOS (rendimiento máximo).




== Solo modo de implementación estándar

La versión de BlueXP backup and recovery solo funciona en el modo de implementación estándar, no en los modos restringido o privado.



== Restricción de nombre de clúster de Windows

El nombre del clúster de Windows no puede contener un carácter de guión bajo (_).



== Problemas de migración de SnapCenter

La migración de recursos de SnapCenter a la BlueXP backup and recovery tiene las siguientes limitaciones.

Para obtener detalles sobre cómo las políticas de SnapCenter migran a las políticas de BlueXP backup and recovery , consulte link:reference-policy-differences-snapcenter.html["Políticas en SnapCenter comparadas con las de BlueXP backup and recovery"] .



=== Limitaciones del grupo de recursos

Si todos los recursos de un grupo de recursos están protegidos y uno de esos recursos también está protegido fuera del grupo de recursos, la migración desde SnapCenter se bloquea.

*Solución alternativa*: proteja el recurso en un grupo de recursos o por sí solo, pero no en ambos.



=== No se admiten recursos con múltiples políticas que utilizan el mismo nivel de programación

No se pueden asignar varias políticas que utilicen el mismo nivel de programación (por ejemplo, por hora, por día, por semana, etc.) a un recurso. La BlueXP backup and recovery no importará esos recursos desde SnapCenter.

*Solución alternativa*: adjunte solo una política que utilice el mismo nivel de programación a un recurso.



=== Las políticas horarias deben comenzar al inicio de la hora

Si tiene una política de SnapCenter que se repite cada hora, pero las horas no tienen intervalos al inicio de la hora, BlueXP backup and recovery no importará el recurso. Por ejemplo, no se admiten políticas con horarios de 1:30, 2:30, 3:30, etc., mientras que sí se admiten políticas con horarios de 1:00, 2:00, 3:00, etc.

*Solución alternativa*: utilice una política que se repita en intervalos de 1 hora comenzando en la parte superior de la hora.



=== No se admiten políticas diarias ni mensuales asociadas a un recurso

Si una política de SnapCenter se repite en intervalos de día y de mes, la BlueXP backup and recovery no importará la política.

Por ejemplo, no puede adjuntar una política diaria (con menos o igual a 7 días o más de 7 días) a un recurso y también adjuntar una política mensual al mismo recurso.

*Solución alternativa*: utilice una política que utilice un intervalo diario o mensual, pero no ambos.



=== Políticas de respaldo a pedido no migradas

La BlueXP backup and recovery no importa políticas de copia de seguridad a pedido desde SnapCenter.



=== Políticas de respaldo de solo registro no migradas

El BlueXP backup and recovery no importa políticas de copia de seguridad de solo registro desde SnapCenter. Si una política de SnapCenter incluye copias de seguridad de solo registro, el BlueXP backup and recovery no importará el recurso.

*Solución alternativa*: utilice una política en SnapCenter que utilice más que solo copias de seguridad de registros.



=== Asignación de hosts

SnapCenter no asigna clústeres de almacenamiento ni máquinas virtuales de asignación (SVM) a los recursos de los hosts, pero BlueXP backup and recovery sí. El clúster de ONTAP local o la SVM no se asignarán a un host en la versión preliminar de BlueXP backup and recovery . Además, BlueXP no admite SVM.

*Solución alternativa*: Antes de importar recursos desde SnapCenter, cree un entorno de trabajo en BlueXP backup and recovery para todos los sistemas de almacenamiento ONTAP locales registrados en SnapCenter local. A continuación, importe los recursos para ese clúster desde SnapCenter a BlueXP backup and recovery.



=== Horarios que no están en intervalos de 15 minutos

Si tiene una programación de políticas de SnapCenter que comienza a una hora determinada y se repite cada cierta cantidad de minutos, pero los minutos no están en intervalos de 15 minutos, la BlueXP backup and recovery no importará la programación.

*Solución alternativa*: utilice SnapCenter para ajustar la política de modo que se repita en intervalos de 15 minutos.



=== Retención de copias de seguridad de registros

Con SnapCenter, puede tener varios valores de retención en varias políticas asociadas a un recurso. Sin embargo, la versión preliminar de BlueXP backup and recovery solo admite un único valor de retención para todas las políticas asociadas a un recurso.
