---
sidebar: sidebar 
permalink: br-limitations-vmware.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, vmware, vcenter 
summary: El servicio de BlueXP backup and recovery necesita primero descubrir los datos para que pueda utilizarlo. Durante el descubrimiento, BlueXP backup and recovery analiza todos los volúmenes y archivos en los entornos de trabajo de su organización. 
---
= Limitaciones conocidas de la BlueXP backup and recovery para cargas de trabajo de VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Las siguientes acciones no son compatibles con la versión preliminar de las cargas de trabajo de VMware en la BlueXP backup and recovery:

* Montar
* Desmontar
* Restaurar a una ubicación alternativa
* Restaurar VMDK
* Adjuntar VMDK
* Desconectar VMDK
* Compatibilidad con vVol
* Compatibilidad con NVMe
* Integración de correo electrónico
* Editar política
* Editar grupo de protección
* Compatibilidad con control de acceso basado en roles (RBAC)

