---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta. 
---
= Preguntas frecuentes sobre la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Estas preguntas frecuentes pueden ser de ayuda si solo está buscando una respuesta rápida a una pregunta.



== Puesta en marcha

*¿Necesita una licencia para utilizar la versión preliminar de BlueXP Backup and Recovery?*

Puede utilizar los siguientes tipos de licencia:

* Regístrate para una prueba gratuita de 30 días.


¿Cómo se activa la BlueXP backup and recovery? No es necesario activar la BlueXP backup and recovery . Esta opción se activa automáticamente en el menú de navegación izquierdo de BlueXP .

Para continuar, debes registrarte o ponerte en contacto con tu representante de ventas de NetApp para probar este servicio. Una vez que utilices BlueXP Connector, incluirá las prestaciones adecuadas para el servicio.

Para comenzar con la BlueXP backup and recovery, haga clic en "Comenzar a descubrir cargas de trabajo" desde su página de inicio.

*¿ La BlueXP backup and recovery está disponible en los modos estándar, restringido y privado?* En este momento, la versión preliminar de la BlueXP backup and recovery solo está disponible en el modo estándar. Manténgase atento para obtener más información.

Para obtener una explicación sobre estos modos en todos los servicios de BlueXP , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implementación de BlueXP"^] .



== Acceso

¿Cuál es la URL de BlueXP backup and recovery ? Para la URL, en un navegador, introduzca: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^] Para acceder a la consola de BlueXP .

* ¿Cómo se manejan los permisos de acceso?* Solo los administradores de la organización tienen la capacidad de iniciar el servicio y detectar cargas de trabajo (porque esto implica comprometerse con el uso de un recurso). Cualquier rol puede realizar interacciones posteriores.

* ¿Qué resolución de dispositivo es la mejor?* La resolución de dispositivo recomendada para la BlueXP backup and recovery es 1920 x 1080 o superior.

*¿Qué navegador debo usar?* Cualquier navegador moderno funcionará.



== Interacción con otros servicios

¿ BlueXP backup and recovery tiene conocimiento de las configuraciones de protección realizadas en NetApp ONTAP? Sí, BlueXP backup and recovery detecta las programaciones de instantáneas configuradas en ONTAP.

*Si establece una política utilizando la BlueXP backup and recovery, ¿tiene que realizar cambios futuros solo en este servicio?* Le recomendamos que realice los cambios de política desde el servicio de BlueXP backup and recovery .



== Cargas de trabajo

*¿Qué compone una carga de trabajo?* Una carga de trabajo es una aplicación para la versión preliminar 2025. Una carga de trabajo incluye todos los volúmenes que utiliza una única instancia de aplicación. Por ejemplo, una instancia de base de datos de Microsoft SQL Server implementada en mssql3.host.com puede tener vol1 y vol2 para sus datos y registros, respectivamente. Estos volúmenes juntos constituyen la carga de trabajo para esa instancia específica de la base de datos.

¿Qué cargas de trabajo admite la BlueXP backup and recovery ?

Para la versión preliminar 2025, la BlueXP backup and recovery puede identificar las siguientes cargas de trabajo: aplicaciones de Microsoft SQL Server.

*¿Qué es una carga de trabajo “protegida”?* En la BlueXP backup and recovery, una carga de trabajo muestra un estado “protegido” cuando tiene una política de detección principal habilitada.

*¿Qué es una carga de trabajo “en riesgo”?* Si una carga de trabajo no tiene habilitada una política de detección primaria, está «en riesgo» aunque tenga habilitada una política de copia de seguridad y Snapshot.

*Se agregó una nueva carga de trabajo, pero aún no aparece* Si agregó una nueva carga de trabajo a su entorno, inicie la detección nuevamente y aplique políticas de protección para proteger ese nuevo recurso.



== Políticas de protección

¿ BlueXP backup and recovery tiene en cuenta las configuraciones de protección realizadas en NetApp ONTAP?

Sí, la BlueXP backup and recovery descubre las programaciones de instantáneas configuradas en ONTAP y si ARP y FPolicy están habilitados en una carga de trabajo detectada. La información que ves inicialmente en Dashboard se suma a otras soluciones y productos de NetApp.

¿ La BlueXP backup and recovery tiene en cuenta las políticas ya creadas en SnapCenter?

Sí, si tiene cargas de trabajo administradas en SnapCenter, las políticas administradas por esos productos se incorporan a la BlueXP backup and recovery.

¿Se pueden modificar las políticas transferidas desde SnapCenter?

Sí, puede modificar las políticas administradas por SnapCenter dentro de la BlueXP backup and recovery.

*Si existen políticas de ONTAP (ya habilitadas en el Administrador del sistema, como ARP, FPolicy y instantáneas), ¿se modifican en la BlueXP backup and recovery?*

No. La BlueXP backup and recovery no modifica ninguna política de detección existente (configuración ARP, FPolicy) de ONTAP.

¿Qué sucede si agrega nuevas políticas en SnapCenter después de registrarse para la BlueXP backup and recovery?

La BlueXP backup and recovery reconoce cualquier política nueva creada en SnapCenter.

*¿Puede cambiar las políticas de ONTAP?*

Sí, puede cambiar las políticas de ONTAP en BlueXP backup and recovery. También puede crear nuevas políticas en BlueXP backup and recovery y aplicarlas a las cargas de trabajo. Esta acción reemplaza las políticas de ONTAP existentes con las creadas en BlueXP backup and recovery.
