---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: Antes de utilizar la BlueXP backup and recovery, realice algunos pasos para configurar los destinos de la copia de seguridad. 
---
= Configure los destinos de copia de seguridad antes de utilizar la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Antes de utilizar la BlueXP backup and recovery, realice algunos pasos para configurar los destinos de la copia de seguridad.

Antes de comenzar, revise link:concept-start-prereq.html["requisitos previos"] para asegurarse de que su entorno esté listo.



== Preparar el destino de la copia de seguridad

Prepare uno o más de los siguientes destinos de respaldo:

* StorageGRID) de NetApp .
+
Consulte https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Descubra StorageGRID"^].

+
Referirse a https://docs.netapp.com/us-en/storagegrid/index.html["Documentación de StorageGRID"^] para obtener detalles sobre StorageGRID.

* Servicios web de Amazon. Consulte https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Documentación de Amazon S3"^].
+
Haga lo siguiente para preparar AWS como destino de respaldo:

+
** Configura una cuenta en AWS.
** Configure los permisos S3 en AWS, que se enumeran en la siguiente sección.
** Para obtener más información sobre la gestión de su almacenamiento de AWS en BlueXP , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestione sus bloques de Amazon S3"^] .




* Microsoft Azure.
+
** Consulte https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Documentación de Azure NetApp Files"^].
** Configura una cuenta en Azure.
** Configurar  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Permisos de Azure"^] en Azure.
** Para obtener detalles sobre cómo administrar su almacenamiento de Azure en BlueXP, consulte  https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gestione sus cuentas de almacenamiento de Azure"^] .




Después de configurar las opciones en el destino de la copia de seguridad, lo configurará posteriormente como destino de copia de seguridad en el servicio de BlueXP backup and recovery . Para obtener más información sobre cómo configurar el destino de la copia de seguridad en el BlueXP backup and recovery, consulte link:br-start-discover-backup-targets.html["Descubrir objetivos de copia de seguridad"] .



== Configure permisos de S3

Necesitará configurar dos conjuntos de permisos de AWS S3:

* Permisos para que el conector cree y gestione el bloque de S3.
* Permisos para el clúster ONTAP en las instalaciones para que pueda leer y escribir datos en el bloque de S3.


.Pasos
. Asegúrese de que el conector tiene los permisos necesarios. Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Permisos de políticas de BlueXP "].
+

NOTE: Cuando cree backups en regiones de AWS China, debe cambiar el nombre de recurso de AWS «arn» en todas las secciones _Resource_ de las políticas de IAM de «aws» a «aws-cn», por ejemplo `arn:aws-cn:s3:::netapp-backup-*`.

. Al activar el servicio, el Asistente de copia de seguridad le solicitará que introduzca una clave de acceso y una clave secreta. Estas credenciales se pasan al clúster de ONTAP para que ONTAP pueda realizar backups y restaurar los datos en el bloque de S3. Para ello, deberá crear un usuario de IAM con los siguientes permisos.
+
Consulte la https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentación de AWS: Crear un rol para delegar permisos en un usuario de IAM"^].

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

