---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Kubernetes 
summary: El servicio de BlueXP backup and recovery primero debe descubrir las cargas de trabajo para que usted pueda utilizar el servicio. 
---
= Descubra las cargas de trabajo de Kubernetes en la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El servicio de BlueXP backup and recovery primero debe descubrir las cargas de trabajo de Kubernetes para que usted pueda utilizar el servicio.

*Rol de BlueXP requerido* Esta tarea requiere el rol de superadministrador de Copia de seguridad y recuperación de servicios de datos.  Conozca más sobrelink:reference-roles.html["Roles y privilegios de los servicios de copia de seguridad y recuperación de datos"] . https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^] .



== Descubra las cargas de trabajo de Kubernetes

En el inventario de copias de seguridad y recuperación, puede detectar las cargas de trabajo de Kubernetes que se ejecutan en su entorno. Al detectar una carga de trabajo, se agrega un clúster de Kubernetes a BlueXP backup and recovery, lo que le permite agregar aplicaciones al clúster y proteger los recursos alojados en él.

.Pasos
. Debe realizar una de las siguientes acciones:
+
** Si está descubriendo cargas de trabajo de Kubernetes por primera vez, en BlueXP backup and recovery, seleccione *Descubrir y administrar* en el tipo de carga de trabajo de Kubernetes.
** Si ya ha descubierto cargas de trabajo de Kubernetes, en BlueXP backup and recovery, seleccione *Inventario* > *Cargas de trabajo* y, luego, seleccione *Descubrir recursos*.


. Seleccione el tipo de carga de trabajo *Kubernetes*.
. Ingrese un nombre de clúster y elija un conector para usar con el clúster.
. Siga las instrucciones de la línea de comandos que aparecen:
+
** Crear un espacio de nombres de protección Trident
** Crear un secreto de Kubernetes
** Agregar un repositorio de Helm
** Instalar Trident Protect y el conector Trident Protect
+
Estos pasos garantizan que la BlueXP backup and recovery puedan interactuar con el clúster.



. Después de completar los pasos, seleccione *Descubrir*.
+
El clúster se agrega al inventario.

. Seleccione *Ver* en la carga de trabajo de Kubernetes asociada para ver la lista de aplicaciones, clústeres y espacios de nombres para esa carga de trabajo.




== Continúe al Panel de control de BlueXP backup and recovery

Para mostrar el panel de control de BlueXP backup and recovery , siga estos pasos.

. Desde el menú superior, seleccione *Panel de control*.
. Revise el estado de la protección de datos. El número de cargas de trabajo en riesgo o protegidas aumenta según las nuevas cargas de trabajo detectadas, protegidas y respaldadas.
+
link:br-use-dashboard.html["Descubra lo que le muestra el Dashboard"].


