---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja sus cargas de trabajo de VMware con la BlueXP backup and recovery de NetApp BlueXP. 
---
= Proteja las cargas de trabajo de VMware con la descripción general de la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja sus cargas de trabajo de VMware con BlueXP backup and recovery. BlueXP backup and recovery ofrece operaciones de copia de seguridad y restauración rápidas, eficientes en espacio, consistentes ante fallos y compatibles con las máquinas virtuales (VM), almacenes de datos y VMDK.

Es posible realizar backups de almacenes de datos en Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform y StorageGRID y restaurar máquinas virtuales en el host del plugin de SnapCenter para VMware vSphere en las instalaciones.

[]
====
*NOTA* Esta función utiliza una versión anterior de la interfaz de usuario de BlueXP backup and recovery . Para cambiar entre las versiones de la interfaz de usuario de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Cambiar a la interfaz de usuario de BlueXP backup and recovery anterior"] .

====
Para obtener instrucciones sobre el uso de la interfaz de usuario de BlueXP backup and recovery anterior, consulte los siguientes temas:
