---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: La BlueXP backup and recovery le permite restaurar aplicaciones que haya protegido con una política de protección. 
---
= Restaurar aplicaciones de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery le permite restaurar aplicaciones protegidas con una política de protección. Para restaurar una aplicación, esta debe tener el estado de protección "Protegido" y una política de protección asociada. Para restaurar una aplicación, utilice un punto de restauración, que consta de la instantánea local, la instantánea secundaria y la copia de seguridad en el almacén de objetos. Puede restaurar una aplicación utilizando el archivo local, secundario o del almacén de objetos.

.Rol BlueXP requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso a BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^] .

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario*.
. Elija una carga de trabajo de Kubernetes y seleccione *Ver* en la columna Hosts para la carga de trabajo.
. En la lista de aplicaciones, elija la aplicación que desee restaurar y seleccione el menú Acciones asociado.
. Seleccione *Ver y restaurar*.
+
Aparece la lista de puntos de restauración.

. Abra el menú Acciones del punto de restauración que desee utilizar y seleccione *Restaurar*.


[discrete]
===== Configuración general

. Seleccione la fuente desde la cual restaurar (local, secundaria o almacén de objetos).
. Seleccione el clúster de destino de la lista *Clúster*.
. Elija el espacio de nombres de destino de restauración (original o nuevo).
+
Tenga en cuenta que no se admite la restauración a un clúster diferente ni al espacio de nombres original.

. Seleccione *Siguiente*.


[discrete]
===== Selección de recursos

. Elija si desea restaurar todos los recursos asociados con la aplicación o utilizar un filtro para seleccionar recursos específicos para restaurar:


[role="tabbed-block"]
====
.Restaurar todos los recursos
--
. Seleccione *Restaurar todos los recursos*.
. Seleccione *Siguiente*.


--
.Restaurar recursos específicos
--
. Seleccione *Recursos selectivos*.
. Seleccione el comportamiento del filtro de recursos. Si selecciona *Incluir*, se restaurarán los recursos seleccionados. Si selecciona *Excluir*, no se restaurarán los recursos seleccionados.
. Seleccione *Añadir reglas* para añadir reglas que definan filtros para seleccionar recursos. Necesita al menos una regla para filtrar recursos.
+
Cada regla puede filtrar según criterios como el espacio de nombres del recurso, las etiquetas, el grupo, la versión y el tipo.

. Seleccione *Guardar* para guardar cada regla.
. Cuando haya agregado todas las reglas que necesita, seleccione *Buscar* para ver los recursos disponibles en el archivo de respaldo que coinciden con sus criterios de filtro.
. Cuando esté satisfecho con los resultados, seleccione *Siguiente*.


--
====
[discrete]
===== Configuración de destino

. Elija restaurar a la clase de almacenamiento predeterminada o a una clase de almacenamiento diferente.
. Opcionalmente, si decide restaurar a una clase de almacenamiento diferente, seleccione una clase de almacenamiento de destino que coincida con cada clase de almacenamiento de origen. La clase de almacenamiento de destino debe estar disponible en el clúster de destino.
. Seleccione *Restaurar*.

