---
sidebar: sidebar 
permalink: br-use-kubernetes-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Puede proteger las aplicaciones de Kubernetes y los datos de aplicaciones desde los sistemas ONTAP locales hasta Amazon Web Services, Microsoft Azure, Google Cloud Platform y StorageGRID, garantizando así la protección de sus datos. 
---
= Descripción general de la gestión de cargas de trabajo de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestión de cargas de trabajo de Kubernetes en BlueXP backup and recovery le permite administrar y proteger sus clústeres y aplicaciones de Kubernetes desde un solo lugar. Puede administrar los recursos y las aplicaciones alojadas en sus clústeres de Kubernetes. También puede administrar la configuración de protección de sus cargas de trabajo de Kubernetes.


NOTE: Esta documentación se proporciona como una vista previa de la tecnología. Durante la vista previa, no se recomienda la funcionalidad de Kubernetes para cargas de trabajo de producción. Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

Puede realizar las siguientes tareas relacionadas con la administración de cargas de trabajo de Kubernetes:
