---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: La BlueXP backup and recovery le permite administrar la información del host de su carga de trabajo, la información de la base de datos y la información de las instancias. Puede ver, editar y eliminar la configuración de protección de su inventario. 
---
= Agregar y proteger aplicaciones de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery le permite administrar la información del host de su carga de trabajo, la información de la base de datos y la información de las instancias. Puede ver, editar y eliminar la configuración de protección de su inventario.

.Rol BlueXP requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso a BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^] .



== Agregar y proteger una nueva aplicación de Kubernetes

El primer paso para proteger las aplicaciones de Kubernetes es crear una aplicación dentro de BlueXP backup and recovery. Al crear una aplicación, BlueXP detecta la aplicación en ejecución en el clúster de Kubernetes.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario* > *Aplicaciones*.
. Seleccione *Crear aplicación*.
. Introduzca un nombre para la aplicación.
. Elija cualquiera de los siguientes campos para buscar los recursos que desea proteger:
+
** Clúster asociado
** Espacios de nombres asociados
** Tipos de recursos
** Selectores de etiquetas


. Opcionalmente, seleccione *Recursos con Alcance del Clúster* para elegir cualquier recurso con alcance a nivel de clúster que no esté incluido en la aplicación. Si los incluye, se añadirán a la aplicación al crearla.
. Seleccione *Buscar* para encontrar los recursos según sus criterios de búsqueda.
. BlueXP muestra una lista de recursos que coinciden con sus criterios de búsqueda.
. Si la lista contiene los recursos que desea proteger, seleccione *Siguiente*.
. En el área *Política*, elija una política de protección existente para proteger la aplicación o cree una nueva política.
. En el área *Prescripts y postscripts*, habilite y configure cualquier gancho de ejecución de prescripts o postscripts que desee ejecutar antes o después de las operaciones de copia de seguridad. Para habilitar prescripts o postscripts, debe haber creado al menos uno. link:br-use-manage-execution-hook-templates.html["plantilla de gancho de ejecución"] .
. Seleccione *Crear*.


.Resultado
La aplicación se crea y aparece en la lista de aplicaciones de la pestaña *Aplicaciones* del inventario de Kubernetes. BlueXP habilita la protección de la aplicación según su configuración, y puede supervisar el progreso en el área *Supervisión* de copias de seguridad y recuperación.



== Proteger una aplicación Kubernetes existente

Habilite una política de protección en una aplicación de Kubernetes que ya haya agregado.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario* > *Aplicaciones*.
. En la lista de aplicaciones, elija la aplicación que desee proteger y seleccione el menú Acciones asociado.
. Seleccione *Proteger*.
. En el área *Política*, elija una política de protección existente para proteger la aplicación o cree una nueva política.
. En el área *Prescripts y postscripts*, habilite y configure cualquier gancho de ejecución de prescript o postscript que desee ejecutar antes o después de las operaciones de copia de seguridad. Puede configurar el tipo de gancho de ejecución, la plantilla que utiliza, los argumentos y los selectores de etiquetas.
. Seleccione *Listo*.


.Resultado
BlueXP habilita la protección de la aplicación según su configuración y puede monitorear el progreso en el área *Monitoreo* de copia de seguridad y recuperación.



== Realice una copia de seguridad de una aplicación de Kubernetes ahora

Cree manualmente una copia de seguridad de una aplicación de Kubernetes para establecer una base para futuras copias de seguridad e instantáneas, o para garantizar que los datos más recientes estén protegidos.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario* > *Aplicaciones*.
. En la lista de aplicaciones, elija una aplicación que desee respaldar y seleccione el menú Acciones asociado.
. Seleccione *Hacer copia de seguridad ahora*.
. Asegúrese de que esté seleccionado el nombre de aplicación correcto.
. Seleccione una política de protección de la lista de políticas.
. Seleccione *Back up*.

