---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-clusters.html 
keywords: discover, backup and recovery, snapcenter, kubernetes, k8s, clusters, applications, inventory 
summary: La BlueXP backup and recovery le permite descubrir y administrar sus clústeres de Kubernetes para que pueda proteger los recursos alojados en los clústeres. 
---
= Gestione clústeres de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery le permite descubrir y administrar sus clústeres de Kubernetes para que pueda proteger los recursos alojados en los clústeres.

.Rol BlueXP requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso a BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^] .



== Editar la información del clúster de Kubernetes

Puede editar un clúster si necesita cambiar su nombre.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario* > *Clústeres*.
. En la lista de clústeres, elija el clúster que desee editar y seleccione el menú Acciones asociado.
. Seleccione *Editar clúster*.
. Realice los cambios necesarios en el nombre del clúster.
. Seleccione *Listo*.




== Eliminar un clúster de Kubernetes

Si ya no necesita proteger los recursos alojados en un clúster de Kubernetes, puede eliminarlo de BlueXP backup and recovery. Eliminar un clúster no elimina el clúster ni sus recursos, sino que solo lo elimina del inventario de BlueXP . Antes de eliminar un clúster, debe desactivar la protección y eliminar las aplicaciones asociadas de BlueXP backup and recovery.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario* > *Clústeres*.
. En la lista de clústeres, elija el clúster que desee editar y seleccione el menú Acciones asociado.
. Seleccione *Eliminar clúster*.
. Revise la información en el cuadro de diálogo de confirmación y seleccione *Eliminar*.

