---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: La BlueXP backup and recovery le permite desproteger y eliminar sus aplicaciones de Kubernetes y los recursos asociados. 
---
= Administrar aplicaciones de Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery le permite desproteger y eliminar sus aplicaciones de Kubernetes y los recursos asociados.

.Rol BlueXP requerido
Administrador de la organización o administrador de SnapCenter . link:reference-roles.html["Obtenga información sobre los roles de acceso a BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso de BlueXP para todos los servicios"^] .



== Desproteger una aplicación de Kubernetes

Puede desproteger una aplicación si ya no desea protegerla. Al desprotegerla, BlueXP backup and recovery deja de protegerla, pero conserva todas las copias de seguridad e instantáneas asociadas.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario*.
. Elija una instancia de Kubernetes y seleccione *Ver* para ver los recursos asociados con esa instancia.
. Seleccione la pestaña *Aplicaciones*.
. En la lista de aplicaciones, elija una aplicación que desee desproteger y seleccione el menú Acciones asociado.
. Seleccione *Desproteger*.
. Lea el aviso y, cuando esté listo, seleccione *Desproteger*.




== Eliminar una aplicación de Kubernetes

Puedes eliminar una aplicación si ya no la necesitas. Al eliminar una aplicación, BlueXP backup and recovery deja de protegerla y elimina todas las copias de seguridad e instantáneas asociadas.

.Pasos
. En la BlueXP backup and recovery, seleccione *Inventario*.
. Elija una instancia de Kubernetes y seleccione *Ver* para ver los recursos asociados con esa instancia.
. Seleccione la pestaña *Aplicaciones*.
. En la lista de aplicaciones, elija la aplicación que desee eliminar y seleccione el menú Acciones asociado.
. Seleccione *Eliminar*.
. Habilite *Eliminar instantáneas y copias de seguridad* para eliminar todas las instantáneas y copias de seguridad de la aplicación.
+

CAUTION: Ya no podrás restaurar la aplicación utilizando estas instantáneas y copias de seguridad.

. Confirme la acción y seleccione *Eliminar*.

