---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Comience a usar la BlueXP backup and recovery verificando la disponibilidad de su entorno operativo, el Conector de BlueXP y su cuenta de BlueXP . Para usar la BlueXP backup and recovery, necesitará estos requisitos previos. 
---
= Requisitos previos para la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comience a usar la BlueXP backup and recovery verificando la disponibilidad de su entorno operativo, el Conector de BlueXP y su cuenta de BlueXP . Para usar la BlueXP backup and recovery, necesitará estos requisitos previos.



== Para ONTAP 9.8 y posterior

Se debe habilitar una licencia de ONTAP One en la instancia de ONTAP local.



== Para copias de seguridad en almacenamiento de objetos

Para utilizar el almacenamiento de objetos como destino de respaldo, necesita una cuenta con AWS S3, Microsoft Azure Blob, StorageGRID u ONTAP y los permisos de acceso adecuados configurados.

* link:prev-ontap-protect-overview.html["Proteja los datos de sus volúmenes de ONTAP"]
* link:br-use-mssql-protect-overview.html["Proteja sus bases de datos de Microsoft SQL Server"]
* link:prev-vmware-protect-overview.html["Proteja las cargas de trabajo de sus máquinas virtuales"]




== En BlueXP

* Un usuario de BlueXP debe tener el rol y los privilegios necesarios para realizar operaciones en cargas de trabajo de Microsoft SQL Server. Para descubrir los recursos, debe tener el rol de superadministrador en BlueXP backup and recovery . Consulte link:reference-roles.html["Acceso a funciones basado en roles BlueXP backup and recovery"] para obtener detalles sobre los roles y permisos necesarios para realizar operaciones en la BlueXP backup and recovery.
* Una organización BlueXP con al menos un conector BlueXP activo que se conecta a clústeres locales de ONTAP o Cloud Volumes ONTAP. Consulte el *proceso de configuración de la vista previa inicial* a continuación.
* Al menos un entorno de trabajo BlueXP con un clúster NetApp ONTAP local o Cloud Volumes ONTAP .
* Un conector BlueXP
+
Consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Aprenda a configurar un conector BlueXP"] y. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^]

+
** La versión preliminar requiere el sistema operativo Ubuntu 22.04 LTS para el Conector.






=== Configure BlueXP

El siguiente paso es configurar BlueXP y el servicio de BlueXP backup and recovery .

Revisión https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^].



=== Crea un conector BlueXP

Deberías comunicarte con tu equipo de productos de NetApp para probar este servicio. Una vez que utilices BlueXP Connector, incluirá las prestaciones adecuadas para el servicio.

Para crear un conector en BlueXP  antes de utilizar el servicio, consulte la documentación de BlueXP  que describe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Cómo crear un conector BlueXP"^].

.Dónde instalar el conector BlueXP
Para completar una operación de restauración, el Conector se puede instalar en las siguientes ubicaciones:

ifdef::aws[]

* Para Amazon S3, el conector se puede implementar en sus instalaciones.


endif::aws[]

ifdef::azure[]

* Para Azure Blob, el conector se puede implementar en sus instalaciones.


endif::azure[]

ifdef::gcp[]

endif::gcp[]

* Para StorageGRID, el conector debe implementarse en sus instalaciones, con o sin acceso a Internet.
* Para ONTAP S3, el conector se puede implementar en sus instalaciones (con o sin acceso a Internet) o en un entorno de proveedor de cloud



NOTE: Las referencias a "sistemas ONTAP locales" incluyen los sistemas FAS y AFF .



== Requisitos de host de Microsoft SQL Server

Para utilizar la BlueXP backup and recovery para cargas de trabajo de SQL Server, necesita los siguientes requisitos previos de tamaño, espacio y sistema host.

[cols="33,66a"]
|===
| Elemento | Requisitos 


| Sistemas operativos  a| 
Microsoft Windows Para obtener la información más reciente sobre las versiones compatibles, consulte  https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] .



| Versiones de Microsoft SQL Server  a| 
Las versiones 2012 y posteriores son compatibles con VMware Virtual Machine File System (VMFS) y VMware Virtual Machine Disk (VMDK) NFS.



| Versión del servidor SnapCenter  a| 
Se requiere la versión 5.0 o superior de SnapCenter Server si va a importar sus datos existentes de SnapCenter a BlueXP backup and recovery.


NOTE: Si ya tiene SnapCenter, primero verifique que cumple con los requisitos previos antes de importar desde SnapCenter. Consulte link:concept-start-prereq-snapcenter-import.html["Requisitos previos para importar recursos desde SnapCenter"].



| RAM mínima para el complemento en el host de SQL Server  a| 
1GB



| Espacio mínimo de instalación y registro para el complemento en el host de SQL Server  a| 
5GB

Asigne suficiente espacio en disco y supervise el consumo de almacenamiento de la carpeta de registros. El espacio de registro necesario varía según el número de copias de seguridad realizadas y la frecuencia de las operaciones de protección de datos. Si no hay suficiente espacio, no se crearán los registros para las operaciones.



| Paquetes de software obligatorios  a| 
* Paquete de alojamiento de ASP.NET Core Runtime 8.0.12 (y todos los parches 8.0.x posteriores)
* PowerShell Core 7.4.2


Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Herramienta de matriz de interoperabilidad de NetApp"^].

|===