---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja sus cargas de trabajo de VMware con la BlueXP backup and recovery de NetApp BlueXP. 
---
= Descripción general de la protección de las cargas de trabajo de las máquinas virtuales en la BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja las cargas de trabajo de sus máquinas virtuales con BlueXP backup and recovery. BlueXP backup and recovery ofrece operaciones de copia de seguridad y restauración rápidas, eficientes en espacio, consistentes ante fallos y compatibles con la máquina virtual (VM), almacenes de datos y VMDK.

Es posible realizar backups de almacenes de datos en Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform y StorageGRID y restaurar máquinas virtuales en el host del plugin de SnapCenter para VMware vSphere en las instalaciones.

[]
====
*NOTA* Para cambiar hacia y desde las cargas de trabajo de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Cambiar a diferentes cargas de trabajo de BlueXP backup and recovery"] .

====
Para obtener instrucciones sobre cómo proteger las cargas de trabajo de las máquinas virtuales, consulte los siguientes temas:

* link:prev-vmware-policy-create.html["Crear una política para cargas de trabajo de VMware"]
* link:prev-vmware-backup-aws.html["Realizar copias de seguridad de almacenes de datos de VMware en Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Realizar copias de seguridad de almacenes de datos de VMware en Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Realizar copias de seguridad de almacenes de datos de VMware en Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Realizar copias de seguridad de almacenes de datos de VMware en StorageGRID"]
* link:prev-vmware-restore.html["Restaurar cargas de trabajo de VMware"]
* link:prev-vmware-manage.html["Administrar la protección para cargas de trabajo de VMware"]

