---
settings:
  name: BlueXP backup and recovery
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Proveedor de cloud
    default: Todos los proveedores de cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de backup y recuperación de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas para las cargas de trabajo de Microsoft SQL Server
      url: "/br-limitations.html"
    - title: Limitaciones conocidas para las cargas de trabajo de volúmenes ONTAP
      url: "/br-reference-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Descubre el backup y la recuperación de BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Requisitos previos para la BlueXP backup and recovery
      url: "/concept-start-prereq.html"
    - title: Configura las licencias para el backup y la recuperación de BlueXP
      url: "/br-start-licensing.html"
    - title: Configure los destinos de copia de seguridad antes de utilizar la BlueXP
        backup and recovery
      url: "/br-start-setup.html"
    - title: Inicie sesión en la BlueXP backup and recovery
      url: "/br-start-login.html"
    - title: Descubrir objetivos de copia de seguridad
      url: "/br-start-discover-backup-targets.html"
    - title: Cambiar a diferentes cargas de trabajo de BlueXP backup and recovery
      url: "/br-start-switch-ui.html"
    - title: Configurar los ajustes generales de BlueXP backup and recovery
      url: "/br-start-configure.html"
  - title: Utilice la BlueXP backup and recovery
    entries:
    - title: Ver el estado de la protección en el Panel de Control
      url: "/br-use-dashboard.html"
    - title: Crear políticas para gobernar las copias de seguridad y restauraciones
      url: "/br-use-policies-create.html"
    - title: Proteger las cargas de trabajo de volumen de ONTAP
      entries:
      - title: Descripción general de las cargas de trabajo de volumen de Protect
          ONTAP
        url: "/prev-ontap-protect-overview.html"
      - title: Planifique su proceso de protección para los volúmenes de ONTAP
        url: "/prev-ontap-protect-journey.html"
      - title: Gestione políticas para volúmenes de ONTAP
        url: "/prev-ontap-policy-manage.html"
      - title: Opciones de política de copia de seguridad a objeto para volúmenes
          ONTAP
        url: "/prev-ontap-policy-object-options.html"
      - title: Administrar las opciones de configuración avanzada de la política de
          copia de seguridad a objeto
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Realice el backup de Cloud Volumes ONTAP en Amazon S3
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Realice un backup de Cloud Volumes ONTAP en Azure Blob
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Realice backups de Cloud Volumes ONTAP en Google Cloud
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: Realice backup de la ONTAP local en Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: Backup de ONTAP en las instalaciones a Azure Blob
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: Realice backup en las instalaciones de ONTAP en Google Cloud
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: Realice un backup del ONTAP en las instalaciones a ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: Realice backup en las instalaciones de ONTAP en StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: Migrar volúmenes mediante SnapMirror a la resincronización en el cloud
        url: "/prev-ontap-migrate-resync.html"
      - title: Gestión de backups de ONTAP
        url: "/prev-ontap-backup-manage.html"
      - title: Restaurar desde backups de ONTAP
        url: "/prev-ontap-restore.html"
    - title: Proteger las cargas de trabajo de Microsoft SQL Server (versión preliminar)
      entries:
      - title: Descripción general de la protección de las cargas de trabajo de Microsoft
          SQL Server
        url: "/br-use-mssql-protect-overview.html"
      - title: Configurar elementos adicionales si se importa desde SnapCenter
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Descubra las cargas de trabajo de Microsoft SQL Server
        url: "/br-start-discover.html"
      - title: Realizar copias de seguridad de las cargas de trabajo de Microsoft
          SQL Server
        url: "/br-use-mssql-backup.html"
      - title: Restaurar cargas de trabajo de Microsoft SQL Server
        url: "/br-use-mssql-restore.html"
      - title: Clonar cargas de trabajo de Microsoft SQL Server
        url: "/br-use-mssql-clone.html"
      - title: Administrar el inventario de Microsoft SQL Server
        url: "/br-use-manage-inventory.html"
      - title: Administrar instantáneas de Microsoft SQL Server
        url: "/br-use-manage-snapshots.html"
      - title: Crear informes de Microsoft SQL Server
        url: "/br-use-reports.html"
    - title: Proteger las cargas de trabajo de las máquinas virtuales
      entries:
      - title: Descripción general de la protección de cargas de trabajo de máquinas
          virtuales
        url: "/prev-vmware-protect-overview.html"
      - title: Requisitos previos para proteger las cargas de trabajo de las máquinas
          virtuales
        url: "/prev-vmware-prereqs.html"
      - title: Registre el host del plugin de SnapCenter para VMware vSphere
        url: "/prev-vmware-register-snapcenter.html"
      - title: Crear una política para realizar copias de seguridad de los datos de
          las máquinas virtuales
        url: "/prev-vmware-policy-create.html"
      - title: Backup de almacenes de datos en Amazon Web Services
        url: "/prev-vmware-backup-aws.html"
      - title: Backup de almacenes de datos en Microsoft Azure
        url: "/prev-vmware-backup-azure.html"
      - title: Realizar backups de almacenes de datos en Google Cloud Platform
        url: "/prev-vmware-backup-gcp.html"
      - title: Realizar backup de almacenes de datos en StorageGRID
        url: "/prev-vmware-backup-storagegrid.html"
      - title: Gestionar la protección de datos de almacenes de datos y equipos virtuales
        url: "/prev-vmware-manage.html"
      - title: Restaurar datos de máquinas virtuales y almacenes de datos
        url: "/prev-vmware-restore.html"
    - title: Proteger las cargas de trabajo de Kubernetes (versión preliminar)
      entries:
      - title: Descripción general de las cargas de trabajo de Protect Kubernetes
        url: "/br-use-kubernetes-protect-overview.html"
      - title: Descubra las cargas de trabajo de Kubernetes
        url: br-start-discover-kubernetes.html
      - title: Agregar y proteger aplicaciones de Kubernetes
        url: "/br-use-protect-kubernetes-applications.html"
      - title: Restaurar aplicaciones de Kubernetes
        url: "/br-use-restore-kubernetes-applications.html"
      - title: Gestione clústeres de Kubernetes
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: Administrar aplicaciones de Kubernetes
        url: "/br-use-manage-kubernetes-applications.html"
      - title: Administrar plantillas de gancho de ejecución para cargas de trabajo
          de Kubernetes
        url: "/br-use-manage-execution-hook-templates.html"
    - title: Supervisar trabajos
      url: "/br-use-monitor-tasks.html"
    - title: Reinicia el backup y la recuperación de BlueXP
      url: "/reference-restart-backup.html"
  - title: Automatización con la API DE REST
    url: "/br-api-backup-restore.html"
  - title: Referencia
    entries:
    - title: Políticas en SnapCenter comparadas con la BlueXP backup and recovery
      url: "/reference-policy-differences-snapcenter.html"
    - title: Roles y privilegios de BlueXP backup and recovery
      url: "/reference-roles.html"
    - title: Niveles de almacenamiento de archivado compatibles con AWS
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: Niveles de almacenamiento de archivo de Azure compatibles
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Niveles de almacenamiento de archivos de Google Cloud compatibles
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
