---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Proveedor de cloud
    default: Todos los proveedores de cloud
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de backup y recuperación de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/reference-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Descubre el backup y la recuperación de BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Configurar la licencia
      url: "/task-licensing-cloud-backup.html"
    - title: Activar operaciones de vista preliminar
      url: "/task-preview-enable.html"
    - title: Supervisar la protección de datos
      entries:
      - title: Informe sobre la cobertura de protección de datos
        url: "/task-report-inventory.html"
      - title: Supervisar el estado de los trabajos de backup y restauración
        url: "/task-monitor-backup-jobs.html"
  - title: Realice backups y restauraciones de datos de ONTAP
    entries:
    - title: Proteja los datos de sus volúmenes de ONTAP
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Planifica tu proceso de protección
      url: "/concept-protection-journey.html"
    - title: Gestione políticas para volúmenes de ONTAP
      url: "/task-create-policies-ontap.html"
    - title: Opciones de políticas de backup en objeto
      url: "/concept-cloud-backup-policies.html"
    - title: Gestione las opciones de copia de seguridad a objeto en Configuración
        avanzada
      url: "/task-manage-backup-settings-ontap.html"
    - title: Realice el backup de Cloud Volumes ONTAP en Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Realice un backup de Cloud Volumes ONTAP en Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Realice backups de Cloud Volumes ONTAP en Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Realice backup de la ONTAP local en Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Backup de ONTAP en las instalaciones a Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Realice backup en las instalaciones de ONTAP en Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Realice un backup del ONTAP en las instalaciones a ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: Realice backup en las instalaciones de ONTAP en StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: Migra volúmenes con SnapMirror a la resincronización en la nube
      url: "/task-migrate-volumes-snapmirror-cloud-resync.html"
    - title: Gestión de backups de ONTAP
      url: "/task-manage-backups-ontap.html"
    - title: Restaurar desde backups de ONTAP
      url: "/task-restore-backups-ontap.html"
  - title: Realice backups y restauraciones de datos de aplicaciones en las instalaciones
    entries:
    - title: Proteja los datos de las aplicaciones locales
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Registre el servidor SnapCenter
      url: "/task-register-snapcenter-server.html"
    - title: Crear una política para realizar backups de aplicaciones
      url: "/task-create-policies-apps.html"
    - title: Realice backup de los datos de las aplicaciones en las instalaciones
        en Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Realice backups de los datos de las aplicaciones en las instalaciones
        en Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: Realice backups de los datos de las aplicaciones en las instalaciones
        en Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Realice backups de los datos de las aplicaciones en las instalaciones
        en StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Gestione la protección de aplicaciones
      url: "/task-manage-app-backups.html"
    - title: Restaure los datos de las aplicaciones en las instalaciones
      entries:
      - title: Restaurar base de datos de Oracle
        url: "/task-restore-oracle-data.html"
      - title: Restaurar base de datos de SQL Server
        url: "/task-restore-sql-data.html"
      - title: Restaurar la base de datos SAP HANA
        url: "/task-restore-hana-backup.html"
      - title: Restaurar bases de datos MongoDB, MySQL y PostgreSQL
        url: "/task-restore-customplugin-backup.html"
  - title: Realizar backups y restaurar los datos de los equipos virtuales
    entries:
    - title: Proteja los datos de los equipos virtuales
      url: "/concept-protect-vm-data.html"
    - title: Registre el host del plugin de SnapCenter para VMware vSphere
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Crear una política para realizar backups de almacenes de datos
      url: "/task-create-policies-vms.html"
    - title: Backup de almacenes de datos en Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Backup de almacenes de datos en Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Realizar backups de almacenes de datos en Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Realizar backup de almacenes de datos en StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Gestionar la protección de datos de almacenes de datos y equipos virtuales
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Restaurar datos de equipos virtuales
      url: "/task-restore-vm-data.html"
  - title: Automatización con la API DE REST
    url: "/api-backup-restore.html"
  - title: Referencia
    entries:
    - title: Niveles de almacenamiento de archivado compatibles con AWS
      url: "/reference-aws-backup-tiers.html"
    - title: Niveles de acceso de archivado de Azure compatibles
      url: "/reference-azure-backup-tiers.html"
    - title: Compatibilidad con niveles de almacenamiento de archivado de Google
      url: "/reference-google-backup-tiers.html"
    - title: Configurar el backup para el acceso de cuentas múltiples en Azure
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Restaurar la base de datos de backup y recuperación de BlueXP en un sitio
        oscuro
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Reinicia el backup y la recuperación de BlueXP
      url: "/reference-restart-backup.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
