---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: Al utilizar el backup y la recuperación de BlueXP en un sitio sin acceso a Internet, lo que se conoce como «modo privado», los datos de configuración de backup y recuperación de BlueXP se copian en el bloque StorageGRID o ONTAP S3 donde se almacenan los backups. Si tienes un problema con el sistema de host del conector de BlueXP en el futuro, puedes implementar un nuevo conector y restaurar los datos críticos de backup y recuperación de BlueXP. 
---
= Restaurar datos de backup y recuperación de BlueXP en un sitio oscuro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al utilizar el backup y la recuperación de BlueXP en un sitio sin acceso a Internet, conocido como _modo privado_, los datos de configuración de backup y recuperación de BlueXP se copian en el bloque StorageGRID o ONTAP S3 donde se almacenan los backups. Si tiene un problema con el sistema de host de conector BlueXP , puede implementar un nuevo conector y restaurar los datos críticos de backup y recuperación de BlueXP .

Cuando utiliza el backup y la recuperación de datos de BlueXP  en un entorno SaaS en el que el conector BlueXP  se implementa en el proveedor de cloud o en su propio sistema host con acceso a Internet, todos los datos importantes de configuración de backup y recuperación de datos de BlueXP  se incluyen en el cloud y se protegen en el cloud. Si tiene un problema con el conector, simplemente cree un nuevo conector y agregue sus entornos de trabajo y los detalles de la copia de seguridad se restaurarán automáticamente.

Existen dos tipos de datos de los que se realiza la copia de seguridad:

* Base de datos de backup y recuperación de BlueXP: Contiene una lista de todos los volúmenes, archivos de backup, políticas de backup y información de configuración.
* Archivos de catálogo indexados: Contiene índices detallados que se utilizan para la función de búsqueda y restauración que hacen que las búsquedas sean rápidas y eficaces cuando se buscan datos de volumen que se desean restaurar.


Se realiza una copia de seguridad de estos datos una vez al día a medianoche, y se conserva un máximo de 7 copias de cada archivo. Si el conector gestiona varios entornos de trabajo de ONTAP en las instalaciones, los archivos de backup y recuperación de BlueXP se ubicarán en el depósito del entorno de trabajo que se activó primero.


TIP: Nunca se incluyen datos de volumen en la base de datos de backup y recuperación de BlueXP o en los archivos de catálogo indexado.



== Restaure los datos de backup y recuperación de BlueXP  en un nuevo conector BlueXP 

Si su conector BlueXP  local tiene un fallo catastrófico, tendrá que instalar un nuevo conector y restaurar los datos de backup y recuperación de BlueXP  en el nuevo conector.

Deberá realizar las siguientes tareas para devolver el sistema de copia de seguridad y recuperación de BlueXP  a un estado de funcionamiento:

* Instale un conector BlueXP nuevo
* Restaura la base de datos de backup y recuperación de BlueXP
* Restaurar los archivos de catálogo indexado
* Redescubra todos sus sistemas ONTAP y StorageGRID en las instalaciones a la interfaz de usuario de BlueXP


Una vez que compruebe que su sistema está en un orden de funcionamiento, le recomendamos que cree nuevos archivos de copia de seguridad.

.Lo que necesitará
Tendrá que acceder a las copias de seguridad de base de datos e índices más recientes desde el bucket de StorageGRID o ONTAP S3 donde se almacenan los archivos de copia de seguridad:

* Archivo de base de datos MySQL de backup y recuperación de BlueXP
+
Este archivo se encuentra en la siguiente ubicación del depósito `netapp-backup-<GUID>/mysql_backup/`, y se nombra `CBS_DB_Backup_<day>_<month>_<year>.sql`.

* Archivo zip de copia de seguridad de catálogo indexado
+
Este archivo se encuentra en la siguiente ubicación del depósito `netapp-backup-<GUID>/catalog_backup/`, y se nombra `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`.





=== Instale un nuevo conector en un nuevo host Linux local

Al instalar un nuevo conector BlueXP, asegúrese de descargar la misma versión de software que había instalado en el conector original. Los cambios periódicos en la estructura de la base de datos de backup y recuperación de BlueXP pueden hacer que las versiones de software más nuevas sean incompatibles con las copias de seguridad de la base de datos originales. Puede hacerlo https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Actualice el software Connector a la versión más reciente después de restaurar la base de datos de copia de seguridad"^].

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Instale el conector BlueXP en un nuevo host Linux local"^]
. Inicie sesión en BlueXP con las credenciales de usuario administrador que acaba de crear.




=== Restaura la base de datos de backup y recuperación de BlueXP

. Copie el backup de MySQL de la ubicación del backup en el nuevo host Connector. Usaremos el nombre de archivo de ejemplo “CBS_DB_Backup_23_05_2023.sql” a continuación.
. Copie el backup en el contenedor de Docker de MySQL mediante uno de los siguientes comandos, en función de si utiliza un contenedor Docker o Podman:
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Introduzca el shell de contenedor MySQL mediante uno de los siguientes comandos, dependiendo de si está utilizando un contenedor Docker o Podman:
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. En el shell del contenedor, despliegue "env".
. Necesitará la contraseña de MySQL DB, así que copie el valor de la clave "MYSQL_ROOT_PASSWORD".
. Restaure la base de datos MySQL de backup y recuperación de BlueXP con el siguiente comando:
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Compruebe que la base de datos MySQL de backup y recuperación de BlueXP se ha restaurado correctamente mediante los siguientes comandos de SQL:
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
Introduzca la contraseña.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
Compruebe si los volúmenes que se muestran son los mismos que los existentes en el entorno original.





=== Restaurar los archivos de catálogo indexado

. Copie el archivo zip de backup del Catálogo indexado (utilizaremos el nombre del archivo de ejemplo «Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip») desde la ubicación del backup al nuevo host de Connector en la carpeta «/opt/application/netapp/cbs».
. Descomprima el archivo Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip con el siguiente comando:
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Ejecute el comando *ls* para asegurarse de que la carpeta “catalogdb1” ha sido creada con las subcarpetas “Cambios” y “Instantáneas” debajo.




=== Detectar los clústeres de ONTAP y los sistemas StorageGRID

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Descubra todos los entornos de trabajo de ONTAP en las instalaciones"^] disponibles en el entorno anterior. Esto incluye el sistema ONTAP que ha utilizado como servidor S3.
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Descubra sus sistemas StorageGRID"^].




=== Configurar los detalles del entorno de StorageGRID

Agregue los detalles del sistema StorageGRID asociado a sus entornos de trabajo de ONTAP tal y como se han configurado en la configuración original del conector con la https://docs.netapp.com/us-en/bluexp-automation/index.html["API de BlueXP"^].

La siguiente información se aplica a las instalaciones de modo privado a partir de BlueXP  3,9.xx. Para versiones anteriores, utilice el siguiente procedimiento: https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite Cloud Backup: Copia de seguridad y restauración de catálogos indexados y de MySQL"^].

Tendrá que realizar estos pasos en cada sistema ONTAP que esté realizando una copia de seguridad de los datos en StorageGRID.

. Extraiga el token de autorización mediante la siguiente API de autenticación/token.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
Aunque la dirección IP, el nombre de usuario y las contraseñas son valores personalizados, el nombre de cuenta no lo es. El nombre de la cuenta es siempre “account-DARKSITE1”.

+
Esta API devolverá una respuesta como la siguiente. Puede recuperar el token de autorización como se muestra a continuación.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Extraiga el ID de entorno de trabajo y el ID de X-Agent mediante la API de uso/externo/recurso.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Esta API devolverá una respuesta como la siguiente. El valor bajo "resourceIdentifier" denota el _WorkingEnvironment ID_ y el valor bajo "agentId" denota _x-agent-id_.

. Actualice la base de datos de copia de seguridad y recuperación de BlueXP  con los detalles del sistema StorageGRID asociado a los entornos de trabajo. Asegúrese de introducir el nombre de dominio completo de la StorageGRID, así como la clave de acceso y la clave de almacenamiento, como se muestra a continuación:
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Comprueba la configuración de backup y recuperación de BlueXP

. Seleccione cada entorno de trabajo de ONTAP y haga clic en *Ver copias de seguridad* junto al servicio copia de seguridad y recuperación del panel derecho.
+
Es necesario ver todos los backups creados para los volúmenes.

. En el Panel de restauración, en la sección Buscar y restaurar, haga clic en *Configuración de indexación*.
+
Asegúrese de que los entornos de trabajo que tenían activada la catalogación indexada anteriormente permanecen habilitados.

. Desde la página Buscar y restaurar, ejecute algunas búsquedas de catálogo para confirmar que la restauración de catálogo indexado se ha completado correctamente.

