---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: Cree el entorno de trabajo Azure NetApp Files y el conector 
---
= Configure Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con BlueXP, deberías crear un entorno de trabajo de Azure NetApp Files para añadir y gestionar volúmenes y servicios de datos adicionales. También debes crear un conector en Azure que permita a BlueXP gestionar los recursos y procesos dentro de tu entorno de nube pública.



== Crear el entorno de trabajo de Azure NetApp Files

Debe crear entornos de trabajo de Azure NetApp Files en los que se alojan las bases de datos. Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Más información sobre Azure NetApp Files"] y.. link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Crear un entorno de trabajo de Azure NetApp Files"].



== Cree un conector

Un administrador de cuenta de BlueXP debería poner en marcha un conector en Azure que permita a BlueXP gestionar recursos y procesos dentro de tu entorno de nube pública.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Cree un conector en Azure desde BlueXP"].

* Asegúrese de que existe conectividad entre el conector y los hosts de la base de datos.
* Si tiene el entorno de trabajo de Azure NetApp Files y las bases de datos en la misma red virtual (vnet), puede implementar el conector en el mismo vnet.
* Si tiene el entorno de trabajo y las bases de datos de Azure NetApp Files en distintas VNets y tiene cargas de trabajo NAS (NFS) configuradas en Azure NetApp Files, puede crear el conector en cualquiera de las VNets.


Después de crear el conector, agregue el entorno de trabajo haciendo clic en *Almacenamiento* > *Lienzo* > *Mis entornos de trabajo* > *Agregar entorno de trabajo*.
