---
sidebar: sidebar 
permalink: reference-roles.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, roles, permissions, access control, role-based access control, rbac 
summary: La BlueXP backup and recovery emplea roles para gobernar el acceso que tiene cada usuario a funciones y acciones específicas. 
---
= BlueXP backup and recovery: gestión de identidades y acceso a las funciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La BlueXP backup and recovery emplea la gestión de identidad y acceso (IAM) para gobernar el acceso que tiene cada usuario a funciones y acciones específicas.

El servicio utiliza los siguientes roles que son específicos para la BlueXP backup and recovery.

* *Superadministrador de copia de seguridad y recuperación*: realiza cualquier acción en la BlueXP backup and recovery.
* *Administrador de copias de seguridad*: realice copias de seguridad en instantáneas locales, replique en almacenamiento secundario y realice copias de seguridad en acciones de almacenamiento de objetos en la BlueXP backup and recovery.
* *Restaurar administrador*: restaure las cargas de trabajo mediante la BlueXP backup and recovery.
* *Administrador de clones*: Clona aplicaciones y datos usando la BlueXP backup and recovery.
* *Visor de copias de seguridad y recuperación*: ve información en la BlueXP backup and recovery, pero no realiza ninguna acción.


Para obtener detalles sobre todos los roles de acceso de BlueXP , consulte  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["La documentación de configuración y administración de BlueXP"^] .

La siguiente tabla indica las acciones que cada función de BlueXP backup and recovery puede realizar.

[cols="20,20,15,15a,15a,15a"]
|===
| Característica y acción | Superadministrador de copias de seguridad y recuperación | Administrador de backups | Restaurar administrador | Administrador clon | Visionador 


| Agregar, editar o eliminar hosts | Sí | No  a| 
No
 a| 
No
 a| 
No



| Instalar complementos | Sí | No  a| 
No
 a| 
No
 a| 
No



| Agregar credenciales (host, instancia, vCenter) | Sí | No  a| 
No
 a| 
No
 a| 
No



| Ver panel y todas las pestañas | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Inicie una prueba gratuita | Sí | No  a| 
No
 a| 
No
 a| 
No



| Inicie la detección de las cargas de trabajo | No | Sí  a| 
Sí
 a| 
Sí
 a| 
No



| Ver información de la licencia | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Activar licencia | Sí | No  a| 
No
 a| 
No
 a| 
No



| Ver anfitriones | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



6+| *Horarios*: 


| Activar horarios | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
No



| Suspender horarios | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
No



6+| *Políticas y protección*: 


| Ver planes de protección | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Crear, modificar o eliminar protección | Sí | Sí  a| 
No
 a| 
No
 a| 
No



| Restaurar cargas de trabajo | Sí | No  a| 
Sí
 a| 
No
 a| 
No



| Crear un clon, dividir un clon o eliminar un clon | Sí | No  a| 
No
 a| 
Sí
 a| 
No



| Crear, modificar o eliminar una política | Sí | Sí  a| 
No
 a| 
No
 a| 
No



6+| *Informes*: 


| Ver informes | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Crear informes | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
No



| Eliminar informes | Sí | No  a| 
No
 a| 
No
 a| 
No



6+| *Importar desde SnapCenter y administrar el host*: 


| Ver datos importados de SnapCenter | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Importar datos desde SnapCenter | Sí | Sí  a| 
No
 a| 
No
 a| 
No



| Administrar (migrar) host | Sí | Sí  a| 
No
 a| 
No
 a| 
No



6+| *Configurar ajustes*: 


| Configure el directorio de registro | Sí | Sí  a| 
Sí
 a| 
No
 a| 
No



| Asociar o eliminar credenciales de instancia | Sí | Sí  a| 
Sí
 a| 
No
 a| 
No



6+| *Cubos*: 


| Ver cubos | Sí | Sí  a| 
Sí
 a| 
Sí
 a| 
Sí



| Crear, editar o eliminar un depósito | Sí | Sí  a| 
No
 a| 
No
 a| 
No

|===