---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: Cree el entorno de trabajo Azure NetApp Files y el conector 
---
= Configure Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con BlueXP, deberías crear un entorno de trabajo de Azure NetApp Files para añadir y gestionar volúmenes y servicios de datos adicionales. También debes crear un conector en Azure que permita a BlueXP gestionar los recursos y procesos dentro de tu entorno de nube pública.



== Crear el entorno de trabajo de Azure NetApp Files

Debe crear entornos de trabajo de Azure NetApp Files en los que se alojan las bases de datos. Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Más información sobre Azure NetApp Files"] y.. link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Crear un entorno de trabajo de Azure NetApp Files"].



== Cree un conector

Un administrador de cuenta de BlueXP debería poner en marcha un conector en Azure que permita a BlueXP gestionar recursos y procesos dentro de tu entorno de nube pública.


NOTE: No puede actualizar el nuevo Connector_id desde la interfaz de usuario.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Cree un conector en Azure desde BlueXP"].

* Debe utilizar el mismo conector para gestionar tanto el entorno de trabajo de Azure NetApp Files como las bases de datos.
* Si tiene el entorno de trabajo de Azure NetApp Files y las bases de datos en el mismo cloud privado virtual (VPC), puede implementar el conector en la misma VPC.
* Si tiene el entorno de trabajo y las bases de datos de Azure NetApp Files en distintos PC y tiene cargas de trabajo NAS (NFS) configuradas en Azure NetApp Files, puede crear el conector en cualquiera de los PC virtuales.


Después de crear el conector, realice lo siguiente:

* Agregue el entorno de trabajo haciendo clic en *Almacenamiento* > *Lienzo* > *Mis entornos de trabajo* > *Agregar entorno de trabajo*.
+
Asegúrese de que hay conectividad desde el conector a los hosts de la base de datos y el entorno de trabajo de Azure NetApp Files. El conector debe conectarse al entorno de trabajo de Azure NetApp Files.

* Copie el ID del conector haciendo clic en *Conector > Administrar conectores* y seleccionando el nombre del conector.

