---
sidebar: sidebar 
permalink: reference-configure-fsx-for-ontap.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP 
summary: Cree el entorno de trabajo FSX para ONTAP y el conector 
---
= Configure FSX para ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con BlueXP, deberías crear un entorno de trabajo FSx para ONTAP para añadir y gestionar volúmenes y servicios de datos adicionales. También debes crear un conector en AWS que permita a BlueXP gestionar los recursos y procesos dentro de tu entorno de nube pública.



== Crear un entorno de trabajo FSX para ONTAP

Debes crear los entornos de trabajo de FSx para ONTAP en los que estén alojadas las bases de datos. Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Comience a utilizar Amazon FSX para ONTAP"] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Crear y gestionar un entorno de trabajo de Amazon FSX para ONTAP"].

Puedes crear el entorno de trabajo de FSx para ONTAP mediante BlueXP o AWS. Si ha creado utilizando AWS, debe descubrir el FSX para sistemas ONTAP en BlueXP.



== Cree un conector

Un administrador de cuenta debe crear un conector en AWS que permita a BlueXP gestionar recursos y procesos dentro de tu entorno de nube pública.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html["Creación de un conector en AWS desde BlueXP"].

* Deberías utilizar el mismo conector para gestionar tanto el entorno de trabajo como las bases de datos de FSx for ONTAP.
* Si tiene el entorno de trabajo de FSx para ONTAP y las bases de datos en el mismo cloud privado virtual (VPC), puede poner en marcha el conector en la misma VPC.
* Si tienes el entorno de trabajo de FSx para ONTAP y las bases de datos en distintos PC:
+
** Si tiene cargas de trabajo NAS (NFS) configuradas en FSx para ONTAP, puede crear el conector en cualquiera de los PC virtuales.
** Si solo tiene cargas de trabajo SAN configuradas y no planea usar ninguna carga de trabajo NAS (NFS), debe crear el conector en la VPC donde se crea el sistema FSx para ONTAP.
+

NOTE: Para usar cargas de trabajo NAS (NFS), debe tener una pasarela de tránsito entre el VPC de la base de datos y Amazon VPC. A la dirección IP de NFS, que es una dirección IP flotante, se puede acceder desde otro VPC, solo mediante una puerta de enlace de tránsito. No podemos acceder a las direcciones IP flotantes mediante la asociación de las VPC.





Después de crear el conector, haga clic en *Almacenamiento* > *Lienzo* > *Mis entornos de trabajo* > *Agregar entorno de trabajo* y siga las indicaciones para agregar el entorno de trabajo. Asegúrese de que existe conectividad desde el conector a los hosts de la base de datos Oracle y el entorno de trabajo de FSx. El conector debe poder conectarse a la dirección IP de administración del clúster del entorno de trabajo de FSx.

* Agregue el entorno de trabajo haciendo clic en *Almacenamiento* > *Lienzo* > *Mis entornos de trabajo* > *Agregar entorno de trabajo*.
+
Asegúrese de que haya conectividad entre el conector y los hosts de la base de datos y el entorno de trabajo de FSx para ONTAP. El conector debe conectarse a la dirección IP de gestión del clúster del entorno de trabajo de FSx para ONTAP.

* Copie el ID del conector haciendo clic en *Conector > Administrar conectores* y seleccionando el nombre del conector.

