---
sidebar: sidebar 
permalink: task-restore-customplugin-backup.html 
keywords: restore, mount application backups, MongoDB, MySQL, PostgreSQL 
summary: Puede restaurar la base de datos SAP HANA desde el cloud al servidor SnapCenter en las instalaciones. 
---
= Restaurar bases de datos MongoDB, MySQL y PostgreSQL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible restaurar bases de datos MongoDB, MySQL y PostgreSQL en cualquier host.

* Pasos*

. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *aplicaciones*.
. En el campo *Filtrar por*, seleccione el filtro *Tipo* y en el menú desplegable seleccione *MongoDB*, *MySQL* o *PostgreSQL*.
. Haga clic en *Ver detalles* correspondiente a la base de datos que desea restaurar y haga clic en *Restaurar*.
. En la página Restore options, especifique una de las siguientes opciones:
+
.. Para el entorno NAS, especifique el FQDN o la dirección IP del host al que se van a exportar los volúmenes restaurados del almacén de objetos.
.. Para el entorno SAN, especifique los iniciadores del host al que se van a asignar las LUN de los volúmenes restaurados desde el almacén de objetos.


. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
. Si no hay suficiente espacio en el almacenamiento de origen o el almacenamiento de origen está inactivo, selecciona *Cambiar ubicación de almacenamiento*.
+
Si selecciona *Cambiar ubicación de almacenamiento*, puede agregar un sufijo al volumen de destino. Si no ha seleccionado la casilla de comprobación, se agrega de forma predeterminada *_restore* al volumen de destino.

. Haga clic en *Siguiente*.
. En la página Storage mapping, especifique los detalles de la ubicación de almacenamiento alternativo donde se almacenarán los datos restaurados del almacén de objetos.
. Haga clic en *Siguiente*.
. Revise los detalles y haga clic en *Restaurar*.


Esta operación solo hace la exportación de almacenamiento del backup seleccionado en el host determinado. Debe montar manualmente el sistema de archivos y activar la base de datos. Después de utilizar el volumen, el administrador de almacenamiento puede eliminar el volumen del clúster de ONTAP.
