---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: Puede restaurar bases de datos de Oracle desde el cloud al servidor de SnapCenter en las instalaciones. 
---
= Restaurar base de datos de Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible restaurar una base de datos de Oracle en la ubicación original o en la ubicación alternativa. Para una base de datos RAC, los datos se restauran en el nodo en las instalaciones donde se creó el backup.

Solo es compatible una base de datos completa con restauración de archivos de control. Si los registros de archivo no están presentes en el AFS, debe especificar la ubicación que contiene los registros de archivo necesarios para la recuperación.


IMPORTANT: No se admite la restauración de archivos individuales (SFR).

* Pasos*

. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *aplicaciones*.
. En el campo *filtro por*, seleccione el filtro *Tipo* y, en la lista desplegable, seleccione *Oracle*.
. Haga clic en *Ver detalles* correspondiente a la base de datos que desea restaurar y haga clic en *Restaurar*.
. En la página Restore options, especifique la ubicación donde desea restaurar los archivos de base de datos.
+
|===
| Si... | Realice lo siguiente... 


 a| 
Desea restaurar a la ubicación original
 a| 
.. Seleccione *Restaurar a la ubicación original*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Haga clic en *Siguiente*.
.. Seleccione *Estado de la base de datos* si desea cambiar el estado de la base de datos al estado requerido para realizar operaciones de restauración y recuperación.
+
Los distintos estados de una base de datos, del más alto al más bajo, son open, mounted, started y shutdown.

+
*** Si la base de datos está en un estado más alto, pero el estado debe cambiarse a un estado más bajo para realizar una operación de restauración, debe seleccionar esta casilla de comprobación.
*** Si la base de datos está en un estado más bajo, pero el estado debe cambiarse a uno más alto para realizar la operación de restauración, el estado de la base de datos se modifica automáticamente aunque no seleccione la casilla de comprobación.
*** Si una base de datos está en el estado open y, para restaurarla, la base de datos necesita que esté en el estado mounted, el estado de la base de datos se modifica únicamente si selecciona esta casilla de comprobación.


.. Especifique el alcance de recuperación.
+
*** Seleccione *All Logs* si desea recuperar la última transacción.
*** Seleccione *Until SCN (System Change Number)* si desea recuperar un SCN específico.
*** Seleccione *Fecha y hora* si desea recuperar un dato y una hora específicos.
+
Debe especificar la fecha y la hora de la zona horaria del host de la base de datos.

*** Seleccione *No recovery* si no desea recuperar.


.. Si los registros de archivos no están presentes en el sistema de archivos activo, debe especificar la ubicación que contiene los registros de archivos necesarios para la recuperación.
.. Seleccione la casilla de comprobación si desea abrir la base de datos después de la recuperación.
+
En una configuración de RAC, solo la instancia de RAC que se usa para la recuperación se abre después de esta.





 a| 
Desea restaurar temporalmente a otro almacenamiento y, a continuación, copiar los archivos restaurados en la ubicación original
 a| 
.. Seleccione *Restaurar a la ubicación original*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Selecciona *Cambiar ubicación de almacenamiento*.
+
Si selecciona *Cambiar ubicación de almacenamiento*, puede agregar un sufijo al volumen de destino. Si no ha seleccionado la casilla de comprobación, se agrega de forma predeterminada *_restore* al volumen de destino.

.. Haga clic en *Siguiente*.
.. En la página Storage mapping, especifique los detalles de la ubicación de almacenamiento alternativo donde los datos restaurados del almacén de objetos se almacenarán temporalmente.
+
Si selecciona un sistema ONTAP en las instalaciones y si no ha configurado la conexión del clúster con el almacenamiento de objetos, se le pedirá información adicional sobre el almacén de objetos.

.. Haga clic en *Siguiente*.
.. Seleccione *Estado de la base de datos* si desea cambiar el estado de la base de datos al estado requerido para realizar operaciones de restauración y recuperación.
+
Los distintos estados de una base de datos, del más alto al más bajo, son open, mounted, started y shutdown.

+
*** Si la base de datos está en un estado más alto, pero el estado debe cambiarse a un estado más bajo para realizar una operación de restauración, debe seleccionar esta casilla de comprobación.
*** Si la base de datos está en un estado más bajo, pero el estado debe cambiarse a uno más alto para realizar la operación de restauración, el estado de la base de datos se modifica automáticamente aunque no seleccione la casilla de comprobación.
*** Si una base de datos está en el estado open y, para restaurarla, la base de datos necesita que esté en el estado mounted, el estado de la base de datos se modifica únicamente si selecciona esta casilla de comprobación.


.. Especifique el alcance de recuperación.
+
*** Seleccione *All Logs* si desea recuperar la última transacción.
*** Seleccione *Until SCN (System Change Number)* si desea recuperar un SCN específico.
*** Seleccione *Fecha y hora* si desea recuperar un dato y una hora específicos.
+
Debe especificar la fecha y la hora de la zona horaria del host de la base de datos.

*** Seleccione *No recovery* si no desea recuperar.


.. Si los registros de archivos no están presentes en el sistema de archivos activo, debe especificar la ubicación que contiene los registros de archivos necesarios para la recuperación.
.. Seleccione la casilla de comprobación si desea abrir la base de datos después de la recuperación.
+
En una configuración de RAC, solo la instancia de RAC que se usa para la recuperación se abre después de esta.





 a| 
Desea restaurar a una ubicación alternativa
 a| 
.. Seleccione *Restaurar a ubicación alternativa*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Si desea restaurar en almacenamiento alternativo, realice lo siguiente:
+
... Selecciona *Cambiar ubicación de almacenamiento*.
+
Si selecciona *Cambiar ubicación de almacenamiento*, puede agregar un sufijo al volumen de destino. Si no ha seleccionado la casilla de comprobación, se agrega de forma predeterminada *_restore* al volumen de destino.

... Haga clic en *Siguiente*.
... En la página Storage mapping, especifique los detalles de la ubicación de almacenamiento alternativo donde los datos del almacén de objetos deben restaurarse.


.. Haga clic en *Siguiente*.
.. En la página Host de Destino, seleccione el host en el que se montará la base de datos.
+
... (Opcional) Para el entorno NAS, especifique el FQDN o la dirección IP del host al que se van a exportar los volúmenes restaurados del almacén de objetos.
... (Opcional) Para el entorno SAN, especifique los iniciadores del host al que se van a asignar las LUN de los volúmenes restaurados desde el almacén de objetos.


.. Haga clic en *Siguiente*.


|===
. Revise los detalles y haga clic en *Restaurar*.


La opción *Restore to alternate location* monta la copia de seguridad seleccionada en el host dado. Debe abrir manualmente la base de datos.

Después de montar el backup, no se podrá volver a montar hasta que se desmonte. Puede utilizar la opción *Unmount* de la interfaz de usuario para desmontar la copia de seguridad.

Para obtener información sobre cómo abrir la base de datos Oracle, consulte, https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_bring_up_Oracle_Database_in_another_NFS_host_after_mounting_storage_from_backup_in_Cloud_Backup_for_Applications["Artículo de base de conocimientos"].
