---
sidebar: sidebar 
permalink: task-register-snapcenter-server.html 
keywords: SnapCenter Server, register 
summary: Realice unos pasos para registrar el servidor SnapCenter. 
---
= Registre el servidor SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solo un usuario con el rol de administrador de SnapCenter puede registrar el host en el que se ejecuta SnapCenter Server 4.6 o una versión posterior. Puedes registrar varios hosts de servidor de SnapCenter en BlueXP.

* Pasos*

. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *aplicaciones*.
. En el menú desplegable *Configuración*, haga clic en *servidores SnapCenter*.
. Haga clic en *Registrar servidor SnapCenter*.
. Especifique los siguientes detalles:
+
.. En el campo servidor SnapCenter, especifique el FQDN o la dirección IP del host SnapCenter Server.
.. En el campo Puerto, especifique el número de puerto en el que se está ejecutando el host del servidor SnapCenter.
+
Debe asegurarse de que el puerto está abierto para que se produzca la comunicación entre SnapCenter Server y BlueXP.

.. En el campo Etiquetas, especifique un nombre de sitio, un nombre de ciudad o cualquier nombre personalizado con el que desee etiquetar el servidor SnapCenter.
+
Las etiquetas están separadas por comas.

.. En el campo Username and Password, especifique las credenciales del usuario con el rol SnapCenterAdmin.


. Seleccione el conector en la lista desplegable *Connector*.
. Haga clic en *Registrar*.


*Después de terminar*

Haga clic en *copia de seguridad y restauración* > *aplicaciones* para ver todas las aplicaciones protegidas con el host de servidor SnapCenter registrado. De forma predeterminada, las aplicaciones se detectan automáticamente cada día, a medianoche.


IMPORTANT: Si se añaden SVM a SnapCenter mediante FQDN o la dirección IP, las aplicaciones que se ejecutan en esas SVM no pueden protegerse. El backup y la recuperación de datos de BlueXP para aplicaciones solo reconoce las SVM que se añaden por nombre o las SVM detectadas por SnapCenter que se añadieron como parte del clúster de ONTAP.

Las aplicaciones admitidas y sus configuraciones son:

* Base de datos de Oracle:
+
** Backups completos (datos + registro) creados con al menos una programación diaria, semanal o mensual
** SAN, NFS, VMDK-SAN, VMDK-NFS Y RDM


* Base de datos Microsoft SQL Server:
+
** Independientes, instancias de clústeres de conmutación por error y grupos de disponibilidad
** Backups completos creados con al menos un programa diario, semanal o mensual
** SAN, VMDK-SAN, VMDK-NFS Y RDM


* Base de datos SAP HANA:
+
** Contenedor único 1.x
** Contenedor de base de datos múltiple 2.x.
** Replicación de sistemas HANA (HSR)
+
Debe tener al menos un backup en las ubicaciones primaria y secundaria. Puede decidir realizar un error proactivo o una conmutación por error diferida al secundario.

** Recursos de volúmenes sin datos (NDV), como los binarios de HANA, el volumen de registro de archivos de HANA, el volumen compartido de HANA, etc.




No se muestran las siguientes bases de datos:

* Bases de datos que no tienen backups
* Bases de datos que solo tienen políticas bajo demanda o por hora
* Bases de datos de Oracle que residen en NVMe

