---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: Registra el host del plugin de SnapCenter para VMware vSphere en BlueXP. 
---
= Registre el host del plugin de SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe registrar el host del plugin de SnapCenter para VMware vSphere en BlueXP para que se muestren los almacenes de datos y las máquinas virtuales. Solo un usuario con acceso administrativo puede registrar el host del plugin de SnapCenter para VMware vSphere.


NOTE: Puede registrar varios hosts del plugin de SnapCenter para VMware vSphere en BlueXP. Sin embargo, una vez registrado, no es posible quitar el host del plugin de SnapCenter para VMware vSphere.

.Pasos
. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *Máquinas virtuales*.
. En el menú desplegable *Configuración*, haga clic en *SnapCenter Plug-in for VMware vSphere*.
. Haga clic en *Registrar el plugin de SnapCenter para VMware vSphere*.
. Especifique los siguientes detalles:
+
.. En el campo SnapCenter Plug-in for VMware vSphere, especifique la dirección FQDN o IP del host del plugin de SnapCenter para VMware vSphere.
.. En el campo Port, especifique el número de puerto en el que ejecuta el host del plugin de SnapCenter para VMware vSphere.
+
Debe asegurarse de que la comunicación esté abierta entre el host del plugin de SnapCenter para VMware vSphere en las instalaciones que se ejecuta en el puerto 8144 predeterminado y la instancia de conector de BlueXP, que puede estar ejecutándose en cualquier proveedor de cloud (Amazon Web Services, Microsoft Azure, Google Cloud Platform) o en las instalaciones.

.. En el campo Username and Password, especifique las credenciales del usuario de vCenter con el rol administrator.


. Haga clic en *Registrar*.


*Después de terminar*

Haga clic en *Backup and recovery* > *Virtual Machines* para ver todos los almacenes de datos y las máquinas virtuales que están protegidas mediante el host del plugin de SnapCenter registrado para VMware vSphere.
