---
sidebar: sidebar 
permalink: task-backup-cloud-native-sql-data.html 
keywords: BlueXP, scheduled backups, on-demand backups, create policy, SQL database 
summary: Cree una política, asigne la política y, a continuación, cree backups bajo demanda de la base de datos de SQL. 
---
= Realice backup de bases de datos nativas en el cloud de Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede crear backups programados o bajo demanda asignando las políticas que ha creado.



== Crear política de backup

Puede ejecutar esta API para crear la política de backups.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backup/policies'

Para obtener más información, consulte: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backup%20Policies/MSSQLBackupPolicyService_CreateMSSQLBackupPolicy[]

Esta API crea un trabajo que se puede rastrear desde la pestaña *Job Monitor* en la interfaz de usuario de BlueXP.



=== Parámetros

|===
| Nombre | Tipo | Obligatorio 


 a| 
nombre
 a| 
cadena
 a| 
Verdadero



 a| 
tipo_backup
 a| 
cadena
 a| 
Verdadero



 a| 
copy_only_backup
 a| 
cadena
 a| 
Falso



 a| 
is_system_defined
 a| 
cadena
 a| 
Falso



 a| 
backup_name_format
 a| 
cadena
 a| 
Verdadero



 a| 
schedule_type
 a| 
cadena
 a| 
Verdadero



 a| 
hora_de_inicio
 a| 
número
 a| 
Verdadero



 a| 
hours_interval
 a| 
número
 a| 
Verdadero



 a| 
minutos_interval
 a| 
número
 a| 
Verdadero



 a| 
retention_type
 a| 
cadena
 a| 
Verdadero



 a| 
retention_count
 a| 
número
 a| 
Verdadero



 a| 
hora_end
 a| 
número
 a| 
Verdadero

|===


=== Respuesta

Si la API se ejecuta correctamente, se muestra el código de respuesta 201.

Ejemplo:

[listing]
----
{
    "_links": {
    "self": {
        "href": "/api/resourcelink"
      }
    }
}
----


== Asigne la política a la instancia de base de datos SQL

Puede ejecutar esta API para asignar políticas a la instancia de la base de datos SQL.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/instances/{id}/policy-assignment'

Donde, _id_ es el identificador de instancia de MSSQL obtenido ejecutando la API de instancia de la base de datos de detección. Para obtener más información, consulte link:task-add-sqlhost-install-plugin-sql.html#discover-the-database-instances["Detectar las instancias de base de datos"].

La matriz de ID es la entrada aquí. Por ejemplo:

[listing]
----
[
  "c9f3e68d-1f9c-44dc-b9af-72a9dfc54320"
]
----
Para obtener más información, consulte: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Policy%20Assignment/PostMSSQLInstanceAssignPolicyRequest[]

Esta API crea un trabajo que se puede rastrear desde la pestaña *Job Monitor* en la interfaz de usuario de BlueXP.



=== Respuesta

Si la API se ejecuta correctamente, se muestra el código de respuesta 202.

Ejemplo:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Cree un backup bajo demanda

Puede ejecutar esta API para crear un backup bajo demanda.

'POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

Para obtener más información, consulte: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/CreateMSSQLBackupRequest[]

Esta API crea un trabajo que se puede rastrear desde la pestaña *Job Monitor* en la interfaz de usuario de BlueXP.



=== Parámetros

|===
| Nombre | Tipo | Obligatorio 


 a| 
id


NOTE: Este es el identificador de la instancia de la base de datos MSSQL.
 a| 
cadena
 a| 
Verdadero



 a| 
resource_type
 a| 
cadena
 a| 
Verdadero



 a| 
id_de_política
 a| 
cadena
 a| 
Verdadero



 a| 
schedule_type
 a| 
cadena
 a| 
Verdadero

|===


=== Respuesta

Si la API se ejecuta correctamente, se muestra el código de respuesta 202.

Ejemplo:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----


== Vea los backups

Puede ejecutar estas API para ver todos los backups y también para ver los detalles de un backup en concreto.

'OBTENGA snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups'

'OBTENGA snapcenter.cloudmanager.cloud.netapp.com/api/mssql/backups/{id}'

Para obtener más información, consulte: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Backups/MSSQLGetBackupsRequest[]



=== Respuesta

Si la API se ejecuta correctamente, se muestra el código de respuesta 200.

Ejemplo:

[listing]
----
{
    "total_records": 1,
    "num_records": 1,
    "records": [
        {
            "backup_id": "602d7796-8074-43fc-a178-eee8c78566ac",
            "resource_id": "a779578d-cf78-46f3-923d-b9223255938c",
            "backup_name": "Hourly_policy2_scspa2722211001_NAMEDINSTANCE1_2023_08_08_07_02_01_81269_0",
            "policy_name": "policy2",
            "schedule_type": "Hourly",
            "start_time": "2023-08-08T07:02:10.203Z",
            "end_time": "0001-01-01T00:00:00Z",
            "backup_status": "success",
            "backup_type": "FullBackup"
        }
    ],
    "_links": {
        "next": {}
    }
}
----