---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory 
summary: Con los informes de backup y recuperación de datos de BlueXP, puedes garantizar que los datos cruciales estén protegidos según las políticas definidas por la organización y respaldar de manera eficiente las auditorías para los procesos de cumplimiento de normativas. Con el informe de inventario de backup, puede visualizar todos los backups de una cuenta, un entorno de trabajo o un inventario de SVM específico. 
---
= Informe sobre la cobertura de protección de datos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con los informes de backup y recuperación de datos de BlueXP, puedes asegurarte de que los datos cruciales estén protegidos según las políticas definidas por la organización y proporcionar auditorías para las necesidades de cumplimiento de normativas.

Los informes de backup y recuperación de BlueXP te ayudan a lograr lo siguiente:

* *Visibilidad de operaciones*: Monitoree sus acuerdos de nivel de servicio con respecto a la protección de datos, la tasa de éxito de respaldo y la alineación de la ventana de respaldo a las necesidades del negocio.
* *Cumplimiento y auditoría*: Utilice los informes operativos y de inventario en sus procesos de auditoría internos y externos para el monitoreo continuo del cumplimiento.



NOTE: Las actividades de informe se supervisan en el registro de supervisión de trabajos para poder auditar todas las actividades. link:task-monitor-backup-jobs.html["Obtenga información sobre la supervisión de trabajos"].



== Alcance de los informes

Los informes de backup y recuperación de BlueXP ofrecen información sobre los siguientes aspectos:

* *Ubicación del conector*: Local o en la nube
* *Fuente*: Cloud Volumes ONTAP, on-premises, aplicaciones o Kubernetes
* *Destino*: Cualquiera de los proveedores de nube, NetApp StorageGRID o ONTAP S3
* *Versiones ONTAP*: 9.13.0




== Cree un informe de inventario de copia de seguridad

En la pestaña Informes de backup y recuperación de BlueXP, puede crear el informe de inventario de backup y filtrar el contenido. Con el informe Backup Inventory, puede ver todos los backups de una cuenta, un entorno de trabajo o un inventario de SVM específicos.

El informe Inventario de copia de seguridad muestra la siguiente información, entre otras cosas:

* De datos, entorno de trabajo y SVM
* Volúmenes protegidos y no protegidos
* Destino de backup
* Aplicación de la política de backup
* Estilo de cifrado (clave gestionada por el proveedor o clave gestionada por el usuario)
* Estado de protección contra bloqueo de datos y ransomware (gobierno, cumplimiento de normativas o ninguno)
* Estado de archivado activado
* Número de copias de backup
* Tipo de backup (backup ad hoc programado o iniciado por el usuario)
* Clase de almacenamiento
* Etiqueta de Snapshot



NOTE: El informe Inventario de backup no incluye información de backup caducada o con errores.

La parte superior del informe incluye un gráfico que muestra la siguiente información:

* Recuento de volúmenes en ámbito con al menos un backup
* Total de volúmenes inactivos más volúmenes activos


El informe Inventario de copia de seguridad muestra los siguientes gráficos:

* *Estado de copia de seguridad del volumen*: Muestra los volúmenes protegidos en comparación con los volúmenes no protegidos para el alcance seleccionado.
* *Volúmenes por recuento de copias de seguridad*: Agrupa volúmenes por el número de copias de seguridad disponibles para este volumen.


.Pasos
. En el menú superior, selecciona *Informes*.
. Seleccione *Inventario de copia de seguridad*.
. Selecciona *Crear informe*.
. Seleccione la cuenta, el entorno de trabajo y la SVM.
+

TIP: Puede seleccionar varios entornos de trabajo y SVM.

. Seleccione el marco de tiempo: Últimas 24 horas, semana o mes.
. (Opcional) Filtrar los resultados por estado del trabajo.
. (Opcional) Exporte el contenido del informe en formato .CSV seleccionando *Descargar CSV*.




== Cree un informe Data Protection Job Activity

La supervisión proactiva puede reducir el esfuerzo necesario para supervisar todos los recursos de su ecosistema. A partir de ONTAP 9.13.0, el informe de actividad de trabajos de protección de datos proporciona información sobre operaciones de Snapshot, backup, clonado y restauración que puede utilizar con la supervisión de acuerdos de nivel de servicio y realizar un seguimiento de las tasas de backup y recuperación.

El informe se aplica a las operaciones de backup y recuperación de BlueXP para Cloud Volumes ONTAP, en las instalaciones, aplicaciones y Kubernetes.

El informe Actividad de trabajo de protección de datos muestra, entre otras cosas, la siguiente información:

* De datos, entorno de trabajo y SVM
* Tipo de trabajo (backup o restauración)
* Nombre del recurso (volumen o aplicación)
* Estado del trabajo
* Horas de inicio y finalización y duración
* Nombre de la política para los trabajos de backup
* Etiqueta de Snapshot para trabajos de backup


Los gráficos de la parte superior de la página muestran la siguiente información:

* Trabajos por tipo
+
** Recuento de trabajos de backup y restauración de volúmenes de ONTAP
** Número de trabajos de backup y restauración de aplicaciones
** Recuento de tareas de backup y restauración de máquinas virtuales
** Recuento de tareas de backup y restauración de Kubernetes


* Actividad laboral diaria


.Pasos
. En el menú superior, selecciona *Informes*.
. Seleccione *Actividad de trabajo de protección de datos*.
. Selecciona *Crear informe*.
. Seleccione la cuenta, el entorno de trabajo y la SVM.
. Seleccione el marco de tiempo: Últimas 24 horas, semana o mes.
. (Opcional) Filtre los resultados por estado de trabajo, tipos de trabajos (backup o restauración) y recurso.
. (Opcional) Exporte el contenido del informe en formato .CSV seleccionando *Descargar CSV*.

