---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: Cree sus propias políticas para proteger la aplicación. 
---
= Crear una política para realizar backups de aplicaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe crear una política para realizar un backup de los datos de la aplicación en el cloud.

.Antes de empezar
* Si desea mover backups del almacén de objetos al almacenamiento de archivado, asegúrese de utilizar la versión de ONTAP requerida.
+
** Si utiliza Amazon Web Services, debe usar ONTAP 9.10.1 o una versión posterior
** Si utiliza Microsoft Azure, debe usar ONTAP 9.10.1 o una versión posterior
** Si utiliza Google Cloud, debería utilizar ONTAP 9.12.1 o una versión posterior


* Debe configurar el nivel de acceso de archivado para cada proveedor de cloud.


.Pasos
. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *aplicaciones*.
. En el menú desplegable Configuración, haga clic en *Directivas* > *Crear directiva*.
. En la sección Policy Details, especifique el nombre de la política.
. En la sección Retention, seleccione uno de los tipos de retención y especifique la cantidad de backups que desea retener.
. Seleccione Primary o Secondary como origen de almacenamiento de backup.
. (Opcional) Si desea mover copias de seguridad del almacén de objetos al almacenamiento de archivado después de un determinado número de días para la optimización de costes, seleccione la casilla de verificación *copias de seguridad de nivel a archivado*.
. Haga clic en *Crear*.
+

NOTE: No se puede editar ni eliminar una directiva asociada a una aplicación.


