---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: Puede restaurar la base de datos de SQL Server desde el cloud al servidor de SnapCenter en las instalaciones. 
---
= Restaurar base de datos de SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede restaurar una base de datos de SQL Server a la ubicación original o a la ubicación alternativa.


NOTE: No se admiten la restauración de archivos únicos (SFR), la recuperación de backups de registros y la propagación de grupos de disponibilidad.

.Pasos
. En la interfaz de usuario de BlueXP, haga clic en *Protección* > *copia de seguridad y recuperación* > *aplicaciones*.
. En el campo *filtro por*, seleccione el filtro *Tipo* y, en la lista desplegable, seleccione *SQL*.
. Haga clic en *Ver detalles* para ver todas las copias de seguridad disponibles.
. Seleccione la copia de seguridad y haga clic en *Restaurar*.
. En la página Restore options, especifique la ubicación donde desea restaurar los archivos de base de datos.
+
|===
| Si... | Realice lo siguiente... 


 a| 
Desea restaurar a la ubicación original
 a| 
.. Seleccione *Restaurar a la ubicación original*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Haga clic en *Siguiente*.




 a| 
Desea restaurar temporalmente a otro almacenamiento y, a continuación, copiar los archivos restaurados en la ubicación original
 a| 
.. Seleccione *Restaurar a la ubicación original*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Selecciona *Cambiar ubicación de almacenamiento*.
+
Si selecciona *Cambiar ubicación de almacenamiento*, puede agregar un sufijo al volumen de destino. Si no ha seleccionado la casilla de comprobación, se agrega de forma predeterminada *_restore* al volumen de destino.

.. Haga clic en *Siguiente*.
.. En la página Storage mapping, especifique los detalles de la ubicación de almacenamiento alternativo donde los datos restaurados del almacén de objetos se almacenarán temporalmente.
.. Haga clic en *Siguiente*.




 a| 
Desea restaurar a una ubicación alternativa
 a| 
.. Seleccione *Restaurar a ubicación alternativa*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Haga clic en *Siguiente*.
.. En la página Destination host, seleccione un nombre de host, proporcione un nombre de base de datos (opcional), seleccione una instancia y especifique las rutas de restauración.
+

NOTE: La extensión de archivo proporcionada en la ruta alternativa debe ser la misma que la del archivo de base de datos original.

.. Haga clic en *Siguiente*.




 a| 
Desea restaurar temporalmente en otro almacenamiento y, a continuación, copiar los archivos restaurados en la ubicación alternativa
 a| 
.. Seleccione *Restaurar a ubicación alternativa*.
.. Si la instantánea se encuentra en el almacenamiento de archivado, seleccione la prioridad para restaurar los datos desde el almacenamiento de archivado.
.. Selecciona *Cambiar ubicación de almacenamiento*.
+
Si selecciona *Cambiar ubicación de almacenamiento*, puede agregar un sufijo al volumen de destino. Si no ha seleccionado la casilla de comprobación, se agrega de forma predeterminada *_restore* al volumen de destino.

.. Haga clic en *Siguiente*.
.. En la página Storage mapping, especifique los detalles de la ubicación de almacenamiento alternativo donde los datos restaurados del almacén de objetos se almacenarán temporalmente.
.. Haga clic en *Siguiente*.
.. En la página Destination host, seleccione un nombre de host, proporcione un nombre de base de datos (opcional), seleccione una instancia y especifique las rutas de restauración.
+

NOTE: La extensión de archivo proporcionada en la ruta alternativa debe ser la misma que la del archivo de base de datos original.

.. Haga clic en *Siguiente*.


|===
. En la opción *Pre-operations*, seleccione una de las siguientes opciones:
+
** Seleccione *Sobrescribir la base de datos con el mismo nombre durante la restauración* para restaurar la base de datos con el mismo nombre.
** Seleccione *mantener la configuración de replicación de bases de datos SQL* para restaurar la base de datos y mantener la configuración de replicación existente.


. En la sección *Post-operations*, para especificar el estado de la base de datos para restaurar registros transaccionales adicionales, seleccione una de las siguientes opciones:
+
** Seleccione *operativo, pero no disponible* si está restaurando todas las copias de seguridad necesarias ahora.
+
Este es el comportamiento predeterminado, que deja la base de datos preparada para su uso revirtiendo las transacciones no comprometidas. No podrá restaurar registros de transacciones adicionales hasta que cree un backup.

** Seleccione *no operativo, pero disponible* para dejar la base de datos no operativa sin revertir las transacciones no comprometidas.
+
Pueden restaurarse registros de transacciones adicionales. No podrá utilizar la base de datos hasta que esta se recupere.

** Seleccione *modo de sólo lectura y disponible* para dejar la base de datos en modo de sólo lectura.
+
Esta opción deshace las transacciones no comprometidas, pero guarda las acciones deshechas en un archivo en espera para que puedan revertirse los efectos de recuperación.

+
Si se habilita la opción Undo directory, se restauran más registros de transacciones. Si la operación de restauración para el registro de transacciones no se realiza correctamente, pueden revertirse los cambios. La documentación de SQL Server contiene más información.



. Haga clic en *Siguiente*.
. Revise los detalles y haga clic en *Restaurar*.

