---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery' 
summary: Descubre las novedades del backup y recuperación de BlueXP. 
---
= Novedades de backup y recuperación de datos de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades del backup y recuperación de BlueXP.



== 27 de septiembre de 2024



=== Compatibilidad con Podman en RHEL 8 o 9 con Browse and Restore

El backup y la recuperación de datos de BlueXP  ahora admite la restauración de archivos y carpetas en Red Hat Enterprise Linux (RHEL) versiones 8 y 9 mediante el uso del motor Podman. Esto se aplica al método de exploración y restauración de backup y recuperación de BlueXP .

El conector BlueXP  versión 3.9.40 admite ciertas versiones de Red Hat Enterprise Linux versiones 8 y 9 para cualquier instalación manual del software Connector en un host RHEL 8 o 9, independientemente de la ubicación, además de los sistemas operativos mencionados en el https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisitos del host"^]. Estas versiones más recientes de RHEL requieren el motor Podman en lugar del motor Docker. Anteriormente, el backup y la recuperación de BlueXP  tenían dos limitaciones cuando se utilizaba el motor Podman. Estas limitaciones se han eliminado.

https://review.docs.netapp.com/us-en/bluexp-backup-recovery_br-se-ja/task-restore-backups-ontap.html["Obtenga más información sobre la restauración de datos de ONTAP a partir de archivos de backup"].



=== Una indexación más rápida por catálogos mejora las tareas de búsqueda y restauración

Esta versión incluye un índice de catálogo mejorado que completa la indexación de línea base mucho más rápido. Una indización más rápida permite utilizar la función de búsqueda y restauración más rápidamente.

https://review.docs.netapp.com/us-en/bluexp-backup-recovery_br-se-ja/task-restore-backups-ontap.html["Obtenga más información sobre la restauración de datos de ONTAP a partir de archivos de backup"].



== 22 de julio de 2024



=== Restaure volúmenes de menos de 1 GB

Con esta versión, ahora puede restaurar volúmenes que creó en ONTAP que tengan menos de 1 GB. El tamaño mínimo de volumen que se puede crear con ONTAP es 20 MB.



=== Consejos sobre cómo mitigar los costes de DataLock

La función DataLock protege los archivos de copia de seguridad de ser modificados o eliminados durante un período de tiempo especificado. Esto es útil para proteger sus archivos contra ataques de ransomware.

Para obtener más información sobre DataLock y consejos sobre cómo mitigar los costes asociados, consulte link:concept-cloud-backup-policies.html["Configuración de políticas de backup en objeto"].



=== Integración de AWS IAM Roles Anywhere

El servicio Roles Anywhere de Amazon Web Services (AWS) Identity and Access Management (IAM) le permite utilizar roles de IAM y credenciales a corto plazo para sus cargas de trabajo _outside_ de AWS para acceder a las API de AWS de forma segura, de la misma manera que utiliza roles de IAM para cargas de trabajo _on_ AWS. Cuando utiliza la infraestructura de claves privadas de IAM Roles Anywhere y los tokens de AWS, no necesita claves de acceso de AWS ni claves secretas a largo plazo. Esto le permite rotar las credenciales con mayor frecuencia, lo que mejora la seguridad.

Con esta versión, el soporte para el servicio AWS IAM Roles Anywhere es una vista previa de la tecnología.

Esto se aplica a la copia de seguridad link:task-backup-to-s3.html["Backups de Cloud Volumes ONTAP en AWS"] y link:task-backup-onprem-to-aws.html["Realizar backups de los datos de ONTAP locales en AWS"].

Consulte https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Backup y recuperación de BlueXP Lanzamiento de julio de 2024"].



=== Restauración de directorios o carpetas de FlexGroup ahora disponible

Anteriormente, se podían restaurar los volúmenes de FlexVol, pero no era posible restaurar carpetas o directorios de FlexGroup. Con ONTAP 9.15.1 P2, puede restaurar carpetas de FlexGroup con la opción Examinar y restaurar.

Con esta versión, el soporte para la restauración de carpetas de FlexGroup es una vista previa de la tecnología.

Para obtener más información, consulte link:task-restore-backups-ontap.html#restore-folders-and-files-using-browse-restore["Restaure carpetas y archivos utilizando examinar  Restore"].

Para obtener más información sobre cómo activarlo manualmente, consulte https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Backup y recuperación de BlueXP Lanzamiento de julio de 2024"].



== 17 de mayo de 2024



=== Limitaciones al utilizar RHEL 8 y RHEL 9 para su conector local

BlueXP Connector versión 3.9.40 es compatible con ciertas versiones de Red Hat Enterprise Linux 8 y 9 para cualquier instalación manual del software Connector en un host RHEL 8 o 9, independientemente de la ubicación además de los sistemas operativos mencionados en el https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisitos del host"^]. Estas versiones más recientes de RHEL requieren el motor Podman en lugar del motor Docker. Actualmente, el backup y la recuperación de BlueXP tienen dos limitaciones al utilizar el motor Podman.

Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["Limitaciones de backup y restauración"] para obtener más detalles.

Los siguientes procedimientos incluyen nuevas instrucciones de Podman:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["Reinicia el backup y la recuperación de BlueXP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Restaurar datos de backup y recuperación de BlueXP en un sitio oscuro"]




== 30 de abril de 2024



=== Capacidad para habilitar o deshabilitar los análisis programados de ransomware

Anteriormente, podía habilitar o deshabilitar los análisis de ransomware, pero no podía hacer esto para los análisis programados.

Con este lanzamiento, ahora puede habilitar o deshabilitar los análisis programados de ransomware en la última copia de Snapshot utilizando la opción de la página Configuración avanzada. Si la activa, las exploraciones se realizan semanalmente de forma predeterminada. Puede cambiar esa programación a días o semanas o deshabilitarla, lo que ahorrará costes.

Consulte la siguiente información para obtener más detalles:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gestionar la configuración de copia de seguridad"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gestione políticas para volúmenes de ONTAP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Configuración de políticas de backup en objeto"]




== 04 de abril de 2024



=== Capacidad de habilitar o deshabilitar los análisis de ransomware

Anteriormente, cuando habilitó la detección de ransomware en una política de backup, los análisis se realizaban automáticamente cuando se creó el primer backup y cuando restauró un backup. Anteriormente, el servicio analizaba todas las copias snapshot y no podía desactivar las exploraciones.

Con este lanzamiento, ahora puede habilitar o deshabilitar los análisis de ransomware en la última copia de Snapshot usando la opción de la página Configuración avanzada. Si la activa, las exploraciones se realizan semanalmente de forma predeterminada.

Consulte la siguiente información para obtener más detalles:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gestionar la configuración de copia de seguridad"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gestione políticas para volúmenes de ONTAP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Configuración de políticas de backup en objeto"]




== 12 de marzo de 2024



=== Capacidad para realizar «Restauraciones rápidas» desde backups en el cloud a volúmenes de ONTAP en las instalaciones

Ahora puede realizar una restauración _rápida_ de un volumen desde un almacenamiento en cloud a un volumen de destino de ONTAP en las instalaciones. Antes, podía realizar una restauración rápida solo en un sistema Cloud Volumes ONTAP. La restauración rápida es ideal para situaciones de recuperación ante desastres en las que se necesita proporcionar acceso a un volumen lo antes posible. Una restauración rápida es mucho más rápida que la restauración de volúmenes completos; restaura los metadatos desde una snapshot de la nube a un volumen de destino de ONTAP. La fuente podría ser AWS S3, Azure Blob, Google Cloud Services o NetApp StorageGRID.

El sistema de destino local de ONTAP debe ejecutar ONTAP versión 9.14.1 o posterior.

Puede hacerlo mediante el proceso Examinar y Restaurar, no mediante el proceso Buscar y Restaurar.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Restaurar datos de ONTAP de archivos de backup"].



=== Capacidad de restaurar archivos y carpetas desde copias de Snapshot y replicación

Anteriormente, solo podía restaurar archivos y carpetas desde copias de backup en AWS, Azure y Google Cloud Services. Ahora puede restaurar archivos y carpetas desde copias Snapshot locales y desde copias de replicación.

Puede realizar esta función mediante el proceso de búsqueda y restauración, no mediante el proceso de exploración y restauración.



== 01 de febrero de 2024



=== Mejoras en el backup y recuperación de datos de BlueXP para máquinas virtuales

* Soporte para la restauración de máquinas virtuales a una ubicación alternativa
* Compatibilidad con almacenes de datos desprotegidos




== 15 de diciembre de 2023



=== Informes disponibles para las copias Snapshot locales y de replicación

Anteriormente, se podían generar informes solo con copias de backup. Ahora puede crear informes sobre copias Snapshot locales y replicar también copias Snapshot.

Con estos informes, puede hacer lo siguiente:

* Asegúrese de que los datos críticos estén protegidos según la política de su organización.
* Asegúrese de que los backups se ejecuten sin problemas para un grupo de volúmenes.
* Ofrecen pruebas de protección de sus datos de producción.


Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Informe sobre la cobertura de protección de datos"].



=== Etiquetado personalizado disponible en los volúmenes para ordenarlos y filtrarlos

Ahora puede agregar etiquetas personalizadas a volúmenes a partir de ONTAP 9.13.1 para que pueda agrupar volúmenes dentro de entornos de trabajo y entre entornos. Si hace esto, podrá ordenar los volúmenes en las páginas de interfaz de usuario de backup y recuperación de BlueXP y filtrar en informes.



=== Backups de catálogo retenidos durante 30 días

Anteriormente, se conservaban Catalog.zip backups durante 7 días. Ahora, se retienen durante 30 días.

Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Restaura los datos de backup y recuperación de BlueXP en sitios oscuros"].



== 23 de octubre de 2023



=== creación de políticas de copia de seguridad de 3-2-1 durante la activación de la copia de seguridad

Anteriormente, había que crear políticas personalizadas antes de iniciar una snapshot, replicación o backup. Ahora, puedes crear una política durante el proceso de activación de backup con la interfaz de usuario de backup y recuperación de BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Obtenga más información sobre las políticas"].



=== Soporte para la restauración rápida bajo demanda de volúmenes ONTAP

Ahora, el backup y la recuperación de datos de BlueXP permite realizar una «restauración rápida» de un volumen desde el almacenamiento en cloud a un sistema Cloud Volumes ONTAP. La restauración rápida es ideal para situaciones de recuperación ante desastres en las que se necesita proporcionar acceso a un volumen lo antes posible. Una restauración rápida restaura los metadatos del archivo de backup a un volumen en lugar de restaurar todo el archivo de backup.

El sistema de destino de Cloud Volumes ONTAP debe ejecutar ONTAP versión 9.13.0 o posterior. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Obtenga más información sobre la restauración de datos"].

El monitor de tareas de backup y recuperación de BlueXP también muestra información sobre el progreso de los trabajos de restauración rápidos.



=== Soporte para los trabajos programados en Job Monitor

El Job Monitor de backup y recuperación de BlueXP supervisaba previamente trabajos de backup y restauración programados de volumen a almacén de objetos, pero no trabajos de Snapshot, replicación, backup y restauración locales que se habían programado a través de la interfaz de usuario o la API.

El supervisor de tareas de backup y recuperación de BlueXP ahora incluye trabajos programados para copias Snapshot locales, replicaciones y backups en el almacenamiento de objetos.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Obtenga más información sobre el supervisor de trabajos actualizado"].



== 13 de octubre de 2023



=== Mejoras en el backup y recuperación de datos de BlueXP para aplicaciones (nativas en la nube)

* Base de datos de Microsoft SQL Server
+
** Admite el backup, la restauración y la recuperación de bases de datos de Microsoft SQL Server que residen en Amazon FSx para NetApp ONTAP
** Todas las operaciones solo se admiten mediante las API de REST.


* Sistemas SAP HANA
+
** Durante la actualización del sistema, el montaje y el desmontaje automáticos de los volúmenes se ejecutan usando flujos de trabajo en lugar de scripts
** Admite adición, eliminación, edición, eliminación, mantenimiento, y actualice el host del plugin mediante la interfaz de usuario






=== Mejoras en el backup y la recuperación de BlueXP para aplicaciones (híbrida)

* Admite el bloqueo de datos y la protección contra ransomware
* Admite el movimiento de backups desde StorageGRID al nivel de archivado
* Admite el backup de datos de aplicaciones MongoDB, MySQL y PostgreSQL desde sistemas ONTAP en las instalaciones en Amazon Web Services, Microsoft Azure, Google Cloud Platform y StorageGRID. Puede restaurar los datos cuando sea necesario.




=== Mejoras en el backup y recuperación de datos de BlueXP para máquinas virtuales

* Compatibilidad con el modelo de implementación de proxy de conector




== 11 de septiembre de 2023



=== Gestión de nuevas políticas para datos de ONTAP

Esta versión incluye la capacidad dentro de la interfaz de usuario de crear políticas Snapshot personalizadas, políticas de replicación y políticas para backups en el almacenamiento de objetos para los datos de ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Obtenga más información sobre las políticas"].



=== Soporte para restaurar archivos y carpetas a partir de volúmenes en el almacenamiento de objetos ONTAP S3

Anteriormente, no era posible restaurar archivos y carpetas con la función «Examinar y restaurar» cuando se realizaban backups de volúmenes en el almacenamiento de objetos de ONTAP S3. Esta versión elimina esa restricción.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Obtenga más información sobre la restauración de datos"].



=== Capacidad de archivar los datos de backup de forma inmediata, en lugar de escribir primero en almacenamiento estándar

Ahora puede enviar sus archivos de copia de seguridad inmediatamente al almacenamiento de archivado, en lugar de escribir los datos en el almacenamiento en la nube estándar. Esto puede ser especialmente útil para los usuarios que rara vez necesitan acceder a los datos de backups en la nube o los usuarios que están sustituyendo una copia de seguridad en un entorno de cinta.



=== Compatibilidad adicional para realizar backups y restaurar volúmenes de SnapLock

Ahora, los backups y la recuperación de datos pueden realizar backups tanto de los volúmenes de FlexVol como de FlexGroup que estén configurados mediante el modo de protección SnapLock Enterprise. Los clústeres deben ejecutar ONTAP 9,14 o superior para esta compatibilidad. El backup de los volúmenes de FlexVol con el modo SnapLock Enterprise se admite desde la versión 9.11.1 de ONTAP. Las versiones anteriores de ONTAP no ofrecen compatibilidad para realizar backups de volúmenes de protección de SnapLock.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Obtenga más información sobre la protección de datos de ONTAP"].



== 1 de agosto de 2023

[IMPORTANT]
====
* Debido a una mejora importante de la seguridad, su conector ahora requiere acceso saliente a Internet a un punto final adicional para administrar los recursos de copia de seguridad y recuperación dentro de su entorno de nube pública. Si este punto final no se ha agregado a la lista de permitidos en su firewall, verá un error en la interfaz de usuario sobre el servicio no disponible o el error al determinar el estado del servicio:
+
\https://netapp-cloud-account.auth0.com

* Ahora es necesaria una suscripción PAYGO de backup y recuperación cuando utilice el paquete «CVO Professional» que le permite agrupar el backup y la recuperación de datos de Cloud Volumes ONTAP y BlueXP. Esto no era necesario en el pasado. No se incurrirá en cargos en la suscripción de backup y recuperación para los sistemas Cloud Volumes ONTAP que cumplan los requisitos, pero esto es necesario para configurar el backup en cualquier volumen nuevo.


====


=== Se ha añadido soporte para realizar backups de volúmenes en buckets en sistemas ONTAP configurados con S3

Ahora puede usar un sistema ONTAP configurado para el servicio de almacenamiento simple (S3) para realizar backups de volúmenes en el almacenamiento de objetos. Esto es compatible con los sistemas ONTAP tanto en las instalaciones como con los sistemas Cloud Volumes ONTAP. Esta configuración es compatible con implementaciones de cloud y en ubicaciones locales sin acceso a Internet (una puesta en marcha de modo «privado»).

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Leer más"].



=== Ahora puede incluir Snapshots existentes de un volumen protegido en sus archivos de respaldo

Anteriormente, había tenido la capacidad de incluir copias Snapshot existentes de volúmenes de lectura y escritura en su archivo de backup inicial a un almacenamiento de objetos (en lugar de empezar con la copia Snapshot más reciente). En el archivo de backup no se incluyeron las copias Snapshot existentes de volúmenes de solo lectura (volúmenes de protección de datos). Ahora puede optar por incluir copias Snapshot más antiguas en el archivo de backup para volúmenes «DP».

El asistente de copia de seguridad muestra un aviso al final de los pasos de copia de seguridad, donde puede seleccionar estas copias de Snapshot existentes.



=== El backup y la recuperación de BlueXP ya no admiten el backup automático de volúmenes añadidos en el futuro

Anteriormente, podía marcar una casilla en el asistente de backup para aplicar la política de backup seleccionada a todos los futuros volúmenes añadidos al clúster. Esta función se ha eliminado en función de los comentarios del usuario y la falta de uso de esta función. Debe habilitar manualmente los backups de los nuevos volúmenes que se hayan agregado al clúster.



=== La página Control de trabajos se ha actualizado con nuevas funciones

La página Job Monitoring ahora proporciona más información relacionada con la estrategia de copia de seguridad 3-2-1. El servicio también proporciona notificaciones de alerta adicionales relacionadas con la estrategia de backup.

El filtro de tipo de ciclo de vida de la copia de seguridad ha cambiado a «Retención». Use este filtro para realizar un seguimiento del ciclo de vida del backup e identificar la caducidad de todas las copias de backup. El tipo de trabajo «Retención» captura todos los trabajos de eliminación de Snapshot iniciados en un volumen protegido por el backup y la recuperación de BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Obtenga más información sobre el supervisor de trabajos actualizado"].



== 6 de julio de 2023



=== El backup y la recuperación de datos de BlueXP ahora incluye la posibilidad de programar y crear copias de Snapshot y volúmenes replicados

Ahora, el backup y la recuperación de datos de BlueXP te permite implementar una estrategia 3-2-1 en la que puedes tener 3 copias de los datos de origen en 2 sistemas de almacenamiento diferentes junto con una copia 1 en la nube. Después de la activación, tendrá:

* Copia Snapshot del volumen en el sistema de origen
* Se replica el volumen en un sistema de almacenamiento diferente
* Backup del volumen en el almacenamiento de objetos


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["Obtenga más información sobre las nuevas funciones de backup y restauración de espectro completo"].

Esta nueva funcionalidad también se aplica a las operaciones de recuperación. Es posible realizar operaciones de restauración desde una copia Snapshot, desde un volumen replicado o desde un archivo de backup en el cloud. De este modo, tendrá la flexibilidad de elegir el fichero de backup que cumpla sus requisitos de recuperación, incluidos el coste y la velocidad de recuperación.

Tenga en cuenta que esta nueva funcionalidad y esta nueva interfaz de usuario solo se admiten para clústeres que ejecutan ONTAP 9,8 o posterior. Si su clúster tiene una versión de software anterior, puede continuar utilizando la versión anterior de backup y recuperación de BlueXP. Sin embargo, le recomendamos que actualice a una versión compatible de ONTAP para obtener las funciones y la funcionalidad más recientes. Para seguir utilizando la versión anterior del software, siga estos pasos:

. En la ficha *Volumes*, seleccione *Configuración de copia de seguridad*.
. En la página _Backup Settings_, haz clic en el botón de opción para *Mostrar la versión anterior de copia de seguridad y recuperación de BlueXP*.
+
A continuación, puede gestionar los clústeres más antiguos con la versión anterior del software.





=== Capacidad de crear su contenedor de almacenamiento para backup en el almacenamiento de objetos

Cuando cree archivos de backup en el almacenamiento de objetos, de forma predeterminada, el servicio de backup y recuperación creará los buckets en el almacenamiento de objetos para usted. Puede crear los cubos usted mismo si desea utilizar un nombre determinado o asignar propiedades especiales. Si desea crear su propio bucket, debe crearlo antes de iniciar el asistente de activación. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Aprende a crear tus buckets de almacenamiento de objetos"].

Actualmente, esta funcionalidad no es compatible al crear archivos de backup en sistemas StorageGRID.



== 04 de julio de 2023



=== Mejoras en el backup y recuperación de datos de BlueXP para aplicaciones (nativas en la nube)

* Sistemas SAP HANA
+
** Admite la conexión y la restauración de copia de volúmenes sin datos y volúmenes globales sin datos que tienen protección secundaria Azure NetApp Files


* Bases de datos de Oracle
+
** Admite la restauración de bases de datos de Oracle en Azure NetApp Files en una ubicación alternativa
** Admite la catalogación de backups de bases de datos de Oracle en Azure NetApp Files
** Permite poner el host de base de datos en modo de mantenimiento para realizar tareas de mantenimiento






=== Mejoras en el backup y la recuperación de BlueXP para aplicaciones (híbrida)

* Admite la restauración para cambiar la ubicación
* Permite montar backups de base de datos de Oracle
* Admite el traslado de backups desde GCP al nivel de archivado




=== Mejoras en el backup y recuperación de BlueXP para máquinas virtuales (híbridas)

* Admite la protección de almacenes de datos NFS y VMFS
* Permite cancelar el registro del host del plugin de SnapCenter para VMware vSphere
* Permite la actualización y la detección de almacenes de datos y backups más recientes




== 5 de junio de 2023



=== Los volúmenes de FlexGroup pueden realizarse backups y protegerse mediante la protección frente a ransomware y bloqueo de datos

Las políticas de backup para FlexGroup Volumes ahora pueden usar la protección DataLock y Ransomware cuando el clúster ejecuta ONTAP 9.13.1 o posterior.



=== Nuevas funciones de generación de informes

Ahora existe una pestaña Reports en la que se puede generar un informe de Backup Inventory, que incluye todos los backups de una cuenta, un entorno de trabajo o un inventario de SVM específico. También puede crear un informe de actividad de trabajo de protección de datos, que proporciona información sobre operaciones de Snapshot, backup, clonado y restauración que pueden ayudar con la supervisión de los acuerdos de nivel de servicio. Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Informe sobre la cobertura de protección de datos"].



=== Mejoras en Job Monitor

Ahora puede revisar _backup lifecycle_ como un tipo de trabajo en la página Job Monitor, lo que le ayudará a realizar un seguimiento de todo el ciclo de vida de la copia de seguridad. También puedes ver detalles de todas las operaciones en la línea de tiempo de BlueXP. Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Supervisar el estado de los trabajos de backup y restauración"].



=== Alerta de notificación adicional para etiquetas de política no coincidentes

Se ha agregado una nueva alerta de backup que indica que no se han creado los archivos de backup porque las etiquetas de políticas de Snapshot no coinciden. Si el _label_ definido en una política de backup no tiene un _label_ coincidente en la política de Snapshot, no se creará ningún archivo de backup. Deberá usar System Manager o la CLI de ONTAP para añadir la etiqueta faltante a la política de Snapshot del volumen.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Revisa todas las alertas que pueden enviar el backup y la recuperación de BlueXP"].



=== Copia de seguridad automática de los archivos críticos de backup y recuperación de BlueXP en sitios oscuros

Cuando utilizas el backup y la recuperación de BlueXP en un sitio sin acceso a Internet, conocido como puesta en marcha en «modo privado», la información de backup y recuperación de BlueXP se almacena únicamente en el sistema Connector local. Esta nueva funcionalidad realiza backups automáticos de los datos críticos de backup y recuperación de BlueXP en un bloque de su sistema StorageGRID conectado para que pueda restaurar estos datos en un nuevo conector si es necesario. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Leer más"]



== 8 de mayo de 2023



=== Las operaciones de restauración en el nivel de carpetas ahora se admiten desde el almacenamiento de archivado y desde backups bloqueados

Si se configuró un archivo de backup con protección DataLock & Ransomware, o si el archivo de backup reside en el almacenamiento de archivado, ahora se admiten operaciones de restauración a nivel de carpeta si el clúster ejecuta ONTAP 9.13.1 o posterior.



=== Las claves gestionadas por el cliente entre regiones y proyectos se admiten al realizar backups de volúmenes en Google Cloud

Ahora puede elegir un depósito que esté en un proyecto diferente al proyecto de sus claves de cifrado gestionadas por el cliente (CMEK). https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Obtenga más información sobre la configuración de sus propias claves de cifrado gestionadas por el cliente"].



=== Las regiones de AWS China ahora se admiten para los archivos de copia de seguridad

Las regiones AWS China Pekín (cn-north-1) y Ningxia (cn-norwest-1) ahora se admiten como destinos para sus archivos de copia de seguridad si el clúster ejecuta ONTAP 9.12.1 o superior.

Tenga en cuenta que las políticas de IAM asignadas al conector BlueXP deben cambiar el nombre de recurso de AWS «arn» en todas las secciones _Resource_ de «aws» a «aws-cn»; por ejemplo, «arn:aws-cn:S3:::netapp-backup-*». Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Realice backup de los datos de Cloud Volumes ONTAP en Amazon S3"] y https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["Realice un backup de los datos de ONTAP en las instalaciones en Amazon S3"] para obtener más información.



=== Mejoras en el Monitor de trabajo

Los trabajos iniciados por el sistema, como las operaciones de copia de seguridad en curso, ahora están disponibles en la pestaña *Supervisión de trabajos* para sistemas ONTAP locales que ejecuten ONTAP 9.13.1 o superior. Las versiones anteriores de ONTAP mostrarán únicamente los trabajos iniciados por el usuario.



== 14 de abril de 2023



=== Mejoras en el backup y recuperación de datos de BlueXP para aplicaciones (nativas en la nube)

* Bases de datos SAP HANA
+
** Admite la actualización del sistema basada en scripts
** Admite la restauración de archivos únicos si se configura un backup de Azure NetApp Files
** Admite la actualización de plugins


* Bases de datos de Oracle
+
** Mejoras en la implementación de plugins mediante la simplificación de la configuración de usuarios sudo que no son raíz
** Admite la actualización de plugins
** Admite la detección automática y la protección basada en políticas de bases de datos de Oracle en Azure NetApp Files
** Admite la restauración de bases de datos de Oracle a su ubicación original con recuperación granular






=== Mejoras en el backup y la recuperación de BlueXP para aplicaciones (híbrida)

* El backup y recuperación de BlueXP para aplicaciones (híbrida) se basa en el plano de control de SaaS
* Se han modificado las API DE REST híbridas para alinearse con las API nativas del cloud.
* Admite notificaciones por correo electrónico




== 4 de abril de 2023



=== Capacidad para realizar backups de datos en el cloud desde sistemas Cloud Volumes ONTAP en modo «restringido»

Ahora puede realizar un backup de los datos de sistemas de Cloud Volumes ONTAP instalados en AWS, Azure y regiones comerciales de GCP en «modo restringido». Esto requiere que primero instale el conector en la región comercial "restringida". https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtenga más información sobre los modos de implementación de BlueXP"^]. Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Realizar backups de los datos de Cloud Volumes ONTAP en Amazon S3"] y.. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Realizar backups de los datos de Cloud Volumes ONTAP en Azure Blob"].



=== Capacidad para realizar un backup de los volúmenes de ONTAP en las instalaciones en ONTAP S3 mediante la API

Las nuevas funcionalidades en las API te permiten realizar un backup de tus snapshots de volúmenes en ONTAP S3 mediante el backup y la recuperación de BlueXP. Esta funcionalidad solo está disponible para sistemas ONTAP en las instalaciones por el momento. Para obtener instrucciones detalladas, consulte el Blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["Integración con ONTAP S3 como destino"^].



=== Capacidad de cambiar el aspecto de redundancia de zona de su cuenta de almacenamiento de Azure de LRS a ZRS

Al crear backups desde sistemas Cloud Volumes ONTAP en el almacenamiento de Azure, el backup y la recuperación de BlueXP aprovisiona de forma predeterminada el Blob Container con redundancia local (LRS) para la optimización de costes. Puede cambiar esta configuración a redundancia de zona (ZRS) si desea que los datos se repliquen entre zonas diferentes. Consulte las instrucciones de Microsoft para https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["cambiar el modo de replicar la cuenta de almacenamiento"^].



=== Mejoras en el Monitor de trabajo

* Tanto las operaciones de backup y restauración iniciadas por el usuario desde la API e IU de backup y recuperación de BlueXP, como los trabajos iniciados por el sistema, como las operaciones de backup en curso, ahora están disponibles en la pestaña *Supervisión de trabajos* para sistemas Cloud Volumes ONTAP que ejecuten ONTAP 9.13.0 o posterior. Las versiones anteriores de ONTAP mostrarán únicamente los trabajos iniciados por el usuario.
* Además de poder descargar un archivo CSV para generar informes de todos los trabajos, ahora puede descargar un archivo JSON para un solo trabajo y ver sus detalles. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Leer más"].
* Se han añadido dos nuevas alertas de trabajos de copia de seguridad: "Error de trabajo programado" y "el trabajo de restauración se completa pero con advertencias". https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Revisa todas las alertas que pueden enviar el backup y la recuperación de BlueXP"].




== 9 de marzo de 2023



=== Las operaciones de restauración a nivel de carpeta ahora incluyen todas las subcarpetas y archivos

Anteriormente, cuando restauró una carpeta, solo se restauran los archivos de esa carpeta, no se restauran ni las subcarpetas ni los archivos. Ahora, si utiliza ONTAP 9.13.0 o superior, se restauran todas las subcarpetas y los archivos de la carpeta seleccionada. Esto puede ahorrar mucho tiempo y dinero en casos en los que tiene varias carpetas anidadas en una carpeta de nivel superior.



=== Capacidad para realizar backups de datos de sistemas Cloud Volumes ONTAP en ubicaciones con conectividad saliente limitada

Ahora puede realizar backups de datos de sistemas Cloud Volumes ONTAP instalados en regiones comerciales de AWS y Azure en Amazon S3 o Azure Blob. Esto requiere que instale el conector en modo restringido en un host Linux en la región comercial, y que también implemente el sistema Cloud Volumes ONTAP allí. Consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Realizar backups de los datos de Cloud Volumes ONTAP en Amazon S3"] y.. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Realizar backups de los datos de Cloud Volumes ONTAP en Azure Blob"].



=== Varias mejoras en el Monitor de trabajo

* La página Job Monitoring ha agregado filtrado avanzado para que pueda buscar trabajos de backup y restauración por tiempo, carga de trabajo (volúmenes, aplicaciones o máquinas virtuales), tipo de trabajo, estado, entorno de trabajo y máquina virtual de almacenamiento. También puede introducir texto libre para buscar cualquier recurso, por ejemplo, "Application_3".  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["Consulte cómo utilizar los filtros avanzados"].
* Tanto las operaciones de backup y restauración iniciadas por el usuario desde la API e IU de backup y recuperación de BlueXP, como los trabajos iniciados por el sistema, como las operaciones de backup en curso, ahora están disponibles en la pestaña *Supervisión de trabajos* para sistemas Cloud Volumes ONTAP que ejecuten ONTAP 9.13.0 o posterior. Las versiones anteriores de los sistemas Cloud Volumes ONTAP y los sistemas ONTAP en las instalaciones mostrarán solo los trabajos iniciados por el usuario en este momento.




== 6 de febrero de 2023



=== Capacidad para mover archivos de backup antiguos a almacenamiento de archivado de Azure desde sistemas StorageGRID

Ahora puede organizar en niveles archivos de backup antiguos de sistemas StorageGRID en el almacenamiento de archivado en Azure. Esto le permite liberar espacio en sus sistemas de StorageGRID y ahorrar dinero gracias a una clase de almacenamiento económico para archivos de backup antiguos.

Esta funcionalidad está disponible si su clúster local utiliza ONTAP 9.12.1 o posterior y su sistema StorageGRID utiliza 11.4 o posterior. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["Más información aquí"^].



=== La protección de DataLock y Ransomware se puede configurar para archivos de backup en Azure Blob

Ahora, la protección de DataLock y Ransomware es compatible con los archivos de backup almacenados en Azure Blob. Si su sistema Cloud Volumes ONTAP o ONTAP en las instalaciones ejecutan ONTAP 9.12.1 o superior, ahora puede bloquear sus archivos de copia de seguridad y escanearlos para detectar posible ransomware. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Obtenga más información sobre cómo proteger sus backups con la protección DataLock y Ransomware"^].



=== Mejoras en los volúmenes de FlexGroup de backup y restauración

* Ahora puede elegir varios agregados al restaurar un volumen de FlexGroup. En la última versión solo se pudo seleccionar un único agregado.
* Los sistemas Cloud Volumes ONTAP ahora admiten la restauración de volúmenes de FlexGroup. En la última versión solo pudo restaurar a sistemas de ONTAP en las instalaciones.




=== Los sistemas Cloud Volumes ONTAP pueden trasladar los backups más antiguos a un sistema de almacenamiento para archivado de Google

Los archivos de copia de seguridad se crean inicialmente en la clase de almacenamiento de Google Standard. Ahora puedes utilizar las funciones de backup y recuperación de datos de BlueXP para organizar en niveles backups antiguos en el almacenamiento de Google Archive y optimizar aún más los costes. La última versión solo admitía esta funcionalidad con clústeres de ONTAP en las instalaciones. Ahora se admiten los sistemas Cloud Volumes ONTAP implementados en Google Cloud.



=== Las operaciones de restauración de volúmenes ahora permiten seleccionar la SVM donde desea restaurar datos de volúmenes

Ahora puede restaurar datos de volúmenes en diferentes máquinas virtuales de almacenamiento en los clústeres de ONTAP. Anteriormente, no había capacidad para elegir la máquina virtual de almacenamiento.



=== Compatibilidad mejorada con volúmenes en configuraciones de MetroCluster

Al utilizar ONTAP 9.12.1 GA o superior, ahora se admite el backup cuando se conecta al sistema principal en una configuración MetroCluster. Toda la configuración de backup se transfiere al sistema secundario de forma que los backups al cloud continúan automáticamente tras la conmutación.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["Consulte limitaciones de copia de seguridad para obtener más información"].



== 9 de enero de 2023



=== Capacidad de mover archivos de backup antiguos a almacenamiento de archivado AWS S3 desde sistemas StorageGRID

Ahora puede organizar en niveles archivos de backup antiguos de sistemas StorageGRID en almacenamiento de archivado en AWS S3. Esto le permite liberar espacio en sus sistemas de StorageGRID y ahorrar dinero gracias a una clase de almacenamiento económico para archivos de backup antiguos. Puede elegir entre organizar los backups en niveles en el almacenamiento de AWS S3 Glacier o S3 Glacier Deep Archive.

Esta funcionalidad está disponible si su clúster local utiliza ONTAP 9.12.1 o posterior y su sistema StorageGRID utiliza 11.3 o posterior. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["Más información aquí"].



=== Capacidad de seleccionar sus propias claves gestionadas por el cliente para el cifrado de datos en Google Cloud

Al realizar un backup de datos de sus sistemas ONTAP en Google Cloud Storage, ahora puede seleccionar sus propias claves gestionadas por el cliente para el cifrado de datos en el asistente de activación en lugar de usar las claves de cifrado predeterminadas gestionadas por Google. Solo tienes que configurar primero las claves de cifrado gestionadas por el cliente en Google y, a continuación, introducir los detalles al activar el backup y la recuperación de BlueXP.



=== Ya no se necesita el rol de "administrador del almacenamiento" para que la cuenta de servicio cree backups en Google Cloud Storage

En versiones anteriores, se necesitaba el rol «Storage Admin» para la cuenta de servicio que permitía realizar el backup y la recuperación de datos de BlueXP para acceder a buckets de Google Cloud Storage. Ahora puede crear una función personalizada con un conjunto reducido de permisos que se asignarán a la cuenta de servicio. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Descubra cómo preparar Google Cloud Storage para realizar backups"].



=== Se ha agregado compatibilidad para restaurar datos mediante Buscar y restaurar en sitios sin acceso a Internet

Si va a realizar un backup de datos de un clúster de ONTAP en las instalaciones a StorageGRID en un sitio sin acceso a Internet, también conocido como sitio oscuro o sitio sin conexión, ahora puede utilizar la opción Search & Restore para restaurar datos cuando sea necesario. Esta funcionalidad requiere que el conector BlueXP (versión 3.9.25 o superior) esté desplegado en el sitio sin conexión.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["Descubra cómo restaurar datos de ONTAP mediante la función de restauración de  de búsqueda"].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Vea cómo instalar el conector en su sitio sin conexión"].



=== Capacidad de descargar la página resultados de la supervisión de trabajos como un informe .csv

Después de filtrar la página Supervisión de trabajos para mostrar los trabajos y las acciones que le interesan, ahora puede generar y descargar un archivo .csv de esos datos. A continuación, puede analizar la información o enviar el informe a otras personas de su organización. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Vea cómo generar un informe de supervisión de trabajos"].



== 19 de diciembre de 2022



=== Mejoras en Cloud Backup para aplicaciones

* Bases de datos SAP HANA
+
** Admite backup y restauración basadas en políticas de bases de datos SAP HANA que residen en Azure NetApp Files
** Admite directivas personalizadas


* Bases de datos de Oracle
+
** Añada hosts e implemente el plugin automáticamente
** Admite directivas personalizadas
** Admite backup, restauración y clonado basados en políticas de bases de datos de Oracle que residen en Cloud Volumes ONTAP
** Admite backup y restauración basadas en políticas de bases de datos de Oracle que residen en Amazon FSX para ONTAP de NetApp
** Admite la restauración de bases de datos de Oracle mediante método de conexión y copia
** Compatible con Oracle 21c
** Admite el clonado de bases de datos de Oracle nativas en la nube






=== Mejoras de Cloud Backup para máquinas virtuales

* Equipos virtuales
+
** Realice backups de máquinas virtuales desde un almacenamiento secundario en las instalaciones
** Admite directivas personalizadas
** Admite Google Cloud Platform (GCP) para realizar backup de uno o más almacenes de datos
** Admite almacenamiento en cloud de bajo coste, como Glacier, Deep Glacier y Azure Archive






== 6 de diciembre de 2022



=== Cambios de extremo de acceso a Internet saliente del conector requerido

Debido a un cambio en Cloud Backup, debe cambiar los siguientes extremos de conector para que la operación de Cloud Backup se realice correctamente:

[cols="50,50"]
|===
| Extremo antiguo | Nuevo extremo 


| \https://cloudmanager.cloud.netapp.com | \https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
Vea la lista completa de puntos finales de la https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], o. https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] de cloud híbrido.



=== Compatibilidad para seleccionar la clase de almacenamiento Google Archival en la interfaz de usuario

Los archivos de copia de seguridad se crean inicialmente en la clase de almacenamiento de Google Standard. Ahora puede usar la interfaz de usuario de Cloud Backup para organizar los backups anteriores en niveles en el almacenamiento de Google Archive después de unos días, y conseguir una optimización de costes adicional.

Esta funcionalidad actualmente es compatible con clústeres de ONTAP en las instalaciones utilizando ONTAP 9.12.1 o posterior. No está disponible actualmente para los sistemas Cloud Volumes ONTAP.



=== Compatibilidad con volúmenes de FlexGroup

Cloud Backup ahora admite los backups y restauración de volúmenes de FlexGroup. Al usar ONTAP 9.12.1 o superior, puede realizar un backup de FlexGroup Volumes en un almacenamiento en cloud público y privado. Si tiene entornos de trabajo que incluyen volúmenes FlexVol y FlexGroup, una vez que actualice el software ONTAP, puede realizar un backup de cualquiera de los volúmenes FlexGroup de esos sistemas.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["Consulte la lista completa de los tipos de volumen admitidos"].



=== Capacidad de restaurar datos desde backups a un agregado específico en sistemas Cloud Volumes ONTAP

En versiones anteriores solo podía seleccionar el agregado al restaurar datos en sistemas ONTAP en las instalaciones. Esta funcionalidad ahora funciona cuando se restauran datos en sistemas Cloud Volumes ONTAP.



== 2 de noviembre de 2022



=== Posibilidad de exportar copias snapshot más antiguas a sus archivos de backup de referencia

Si hay copias Snapshot locales para los volúmenes en su entorno de trabajo que coincidan con las etiquetas de programación de backup (por ejemplo, diario, semanal, etc.), puede exportar estas copias Snapshot históricas a almacenamiento de objetos como archivos de backup. Esto permite inicializar backups en el cloud al mover copias de Snapshot más antiguas a la copia de backup de referencia.

Esta opción está disponible cuando se activa Cloud Backup en sus entornos de trabajo. También puede cambiar esta configuración más adelante en la https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Advanced Settings"].



=== Cloud Backup ahora se puede utilizar para archivar volúmenes que ya no necesita en el sistema de origen

Ahora es posible eliminar la relación de backup de un volumen. Esto ofrece un mecanismo de archivado si desea detener la creación de nuevos archivos de copia de seguridad y eliminar el volumen de origen, pero conservar todos los archivos de copia de seguridad existentes. Esto le permite restaurar el volumen desde el archivo de backup en el futuro, si es necesario, a la vez que se borra espacio del sistema de almacenamiento de origen. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["Vea cómo"].



=== Se ha añadido soporte para recibir alertas de Cloud Backup por correo electrónico y en el Centro de notificaciones

Cloud Backup se ha integrado en el servicio de notificación de BlueXP. Puede mostrar notificaciones de Cloud Backup haciendo clic en la campana de notificación de la barra de menús de BlueXP. También puede configurar BlueXP para que envíe notificaciones por correo electrónico como alertas, de forma que pueda ser informado de la actividad importante del sistema incluso cuando no haya iniciado sesión en el sistema. El correo electrónico puede enviarse a los destinatarios que tengan que conocer la actividad de backup y restauración. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["Vea cómo"].



=== Nueva página Advanced Settings permite cambiar la configuración de backup a nivel del clúster

Esta nueva página le permite cambiar muchas opciones de backup a nivel del clúster que se establecen al activar Cloud Backup para cada sistema ONTAP. También puede modificar algunos ajustes que se aplican como ajustes de copia de seguridad "predeterminados". El conjunto completo de ajustes de copia de seguridad que puede cambiar incluye:

* Las claves de almacenamiento que otorgan a su sistema ONTAP permiso para acceder al almacenamiento de objetos
* El ancho de banda de red asignado para cargar backups en el almacenamiento de objetos
* La configuración (y la política) automática de backups para volúmenes futuros
* La clase de almacenamiento para archivado (solo AWS)
* Si se incluyen copias snapshot históricas en sus archivos de backup de base iniciales
* Si se eliminan copias Snapshot "anuales" del sistema de origen
* El espacio IP de ONTAP que está conectado al almacenamiento de objetos (en caso de que la selección no sea correcta durante la activación)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Obtenga más información sobre la gestión de configuraciones de backup en el nivel de clúster"].



=== Ahora puede restaurar archivos de copia de seguridad utilizando Buscar y restaurar cuando utilice un conector local

En la versión anterior, se agregó compatibilidad para crear archivos de backup en el cloud público cuando el conector se implementa en sus instalaciones. En esta versión, se ha continuado permitiendo el uso de Search & Restore para restaurar backups de Amazon S3 o Azure Blob cuando el conector se pone en marcha en sus instalaciones. Search & Restore también admite la restauración de backups desde sistemas StorageGRID a sistemas ONTAP en las instalaciones ahora.

En este momento, el conector debe ponerse en marcha en Google Cloud Platform al utilizar la opción de búsqueda y restauración para restaurar backups desde Google Cloud Storage.



=== Se ha actualizado la página Supervisión de trabajos

Se han realizado las siguientes actualizaciones en https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Página Job Monitoring"]:

* Hay una columna para «Carga de trabajo» disponible para que pueda filtrar la página para ver los trabajos de los siguientes servicios de backup: Volúmenes, aplicaciones y máquinas virtuales.
* Puede añadir nuevas columnas para "Nombre de usuario" y "Tipo de trabajo" si desea ver estos detalles para una tarea de copia de seguridad específica.
* En la página Job Details, se muestran todos los subtrabajos que se ejecutan para completar el trabajo principal.
* La página se actualiza automáticamente cada 15 minutos para que siempre vea los resultados más recientes sobre el estado del trabajo. Y puede hacer clic en el botón *Actualizar* para actualizar la página inmediatamente.




=== Mejoras de backup entre cuentas de AWS

Si desea utilizar una cuenta AWS diferente para las copias de seguridad de Cloud Volumes ONTAP que la que está utilizando para los volúmenes de origen, debe añadir las credenciales de la cuenta AWS de destino en BlueXP y debe agregar los permisos "s3:PutBucketPolicy" y "s3:PutketOwnerOwnershipControls" a la función IAM que proporciona permisos para BlueXP. Anteriormente, era necesario configurar muchos ajustes en la consola de AWS, pero ya no es necesario hacerlo.



== 28 de septiembre de 2022



=== Mejoras en Cloud Backup para aplicaciones

* Admite Google Cloud Platform (GCP) y StorageGRID para realizar backups de copias Snapshot consistentes con las aplicaciones
* Crear directivas personalizadas
* Admite almacenamiento de archivado
* Realice un backup de las aplicaciones SAP HANA
* Realizar un backup de aplicaciones de Oracle y SQL que se encuentran en un entorno de VMware
* Realice backups de las aplicaciones del almacenamiento secundario en las instalaciones
* Desactivar las copias de seguridad
* Cancele el registro del servidor SnapCenter




=== Mejoras de Cloud Backup para máquinas virtuales

* Admite StorageGRID para realizar backup de uno o más almacenes de datos
* Crear directivas personalizadas




== 19 de septiembre de 2022



=== La protección DataLock y Ransomware se puede configurar para archivos de copia de seguridad en sistemas StorageGRID

En la última versión, se introdujo _DataLock y Protección ransomware_ para backups almacenados en bloques de Amazon S3. Esta versión amplía el soporte a los archivos de backup almacenados en sistemas StorageGRID. Si el clúster utiliza ONTAP 9.11.1 o posterior y el sistema StorageGRID ejecuta la versión 11.6.0.3 o posterior, esta nueva opción de política de backup está disponible. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Más información sobre cómo usar la protección DataLock y Ransomware para proteger sus backups"^].

Tenga en cuenta que tendrá que ejecutar un conector con la versión 3.9.22 o superior del software. El conector debe estar instalado en sus instalaciones y se puede instalar en un sitio con o sin acceso a Internet.



=== La restauración a nivel de carpeta ya está disponible en los archivos de copia de seguridad

Ahora puede restaurar una carpeta desde un archivo de copia de seguridad si necesita tener acceso a todos los archivos de esa carpeta (directorio o recurso compartido). La restauración de una carpeta es mucho más eficiente que la restauración de un volumen completo. Esta funcionalidad está disponible para las operaciones de restauración mediante el método Browse & Restore y el método Search & Restore cuando se utiliza ONTAP 9.11.1 o posterior. En este momento puede seleccionar y restaurar solo una carpeta única y solo se restauran los archivos de esa carpeta, no se restauran ninguna subcarpeta ni los archivos de dicha carpeta.



=== La restauración a nivel de archivos ahora está disponible desde backups que se han movido a almacenamiento de archivado

En el pasado, solo podía restaurar volúmenes desde archivos de backup que se habían movido a almacenamiento de archivado (solo AWS y Azure). Ahora puede restaurar ficheros individuales a partir de estos ficheros de copia de seguridad archivados. Esta funcionalidad está disponible para las operaciones de restauración mediante el método Browse & Restore y el método Search & Restore cuando se utiliza ONTAP 9.11.1 o posterior.



=== La restauración a nivel de archivo ofrece ahora la opción de sobrescribir el archivo de origen original

Anteriormente, un archivo restaurado en el volumen original siempre se restauró como un archivo nuevo con el prefijo "Restore_<file_name>". Ahora puede optar por sobrescribir el archivo de origen original al restaurar el archivo a la ubicación original del volumen. Esta funcionalidad está disponible para las operaciones de restauración mediante el método Browse & Restore y el método Search & Restore.



=== Arrastre y suelte para habilitar Cloud Backup en los sistemas StorageGRID

Si la https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] El destino de las copias de seguridad existe como un entorno de trabajo en el lienzo, puede arrastrar el entorno de trabajo de ONTAP en las instalaciones al destino para iniciar el asistente de configuración de copia de seguridad en la nube.
