= Versión preliminar de la BlueXP backup and recovery
:allow-uri-read: 




=== Versión preliminar de la BlueXP backup and recovery

Esta versión preliminar de BlueXP backup and recovery ofrece una interfaz de usuario actualizada que permite administrar las cargas de trabajo de Microsoft SQL Server mediante una estrategia de protección 3-2-1, similar a la del servicio de BlueXP backup and recovery . Con esta nueva versión, puede realizar copias de seguridad de estas cargas de trabajo en el almacenamiento principal, replicarlas en el almacenamiento secundario y respaldarlas en el almacenamiento de objetos en la nube.


NOTE: ESTA DOCUMENTACIÓN SE PROPORCIONA COMO UNA PREVISUALIZACIÓN TECNOLÓGICA. Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

Esta versión de BlueXP backup and recovery Preview 2025 incluye las siguientes actualizaciones.

* Una interfaz de usuario rediseñada que proporciona una experiencia más intuitiva para administrar sus tareas de copia de seguridad y recuperación.
* La versión preliminar permite realizar copias de seguridad y restaurar bases de datos de Microsoft SQL Server. (Se añadirá compatibilidad con otras cargas de trabajo en futuras versiones).
* Esta versión integra las capacidades de SnapCenter , lo que le permite administrar y proteger sus recursos de SnapCenter con una estrategia de protección de datos 3-2-1 desde la interfaz de usuario de BlueXP backup and recovery .
* Esta versión le permite importar cargas de trabajo de SnapCenter a la BlueXP backup and recovery.

